randomizer/ApplyRandomizer.py
randomizer/EntranceRando.py
randomizer/Settings.py
randomizer/ShuffleExits.py
randomizer/Spoiler.py

-Got level order rando working
-B.Locker and T&S progression is set to match the new level order
-Confirmed boss location rando still works when level order rando is on

Level Rando fixes

---

randomizer/EntranceRando.py

For one-way transitions, need to first check if they are in shuffled_exit_data and if not, write vanilla exit data

Fix Coupled LZR breaking on one-way transitions not in pool

---

randomizer/ItemPool.py
randomizer/Logic.py
randomizer/LogicFiles/Shops.py
randomizer/Settings.py
randomizer/Spoiler.py
templates/overworld.html.jinja2
templates/rando_options.html.jinja2

Adds a setting that randomizes the medal requirement for jetpac in a range of 4 to 15 with an average of 10. This PR adds the toggle in the UI as well as the code to set it, and write the amount set in the spoiler for humans and the rom.
Also took out all the code that was treating the Sniper Sight as a special case that wasn't given when starting with all moves, since the lag issue was resolved.
Also I noticed that bananaport rando setting wasn't being displayed in the spoiler so I added that.

Add setting to randomize medal requirement, take away sniper scope special cases

---

randomizer/Settings.py
ui/__init__.py

Now that cookies work on cosmetics fixed the color/music options not being disabled if 'Randomize All' is already on.

Fixed Color options not disabling if Randomize All is already selected.

---

randomizer/Patching/CosmeticColors.py
templates/cosmetics.html.jinja2

Removed 'Red' as an option for Tiny's color until crash is fixed.

No more Pirate Tiny until crash is fixed.

---

randomizer/CollectibleLogicFiles/FungiForest.py
randomizer/Enums/Time.py
randomizer/Fill.py
randomizer/Logic.py
randomizer/LogicClasses.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/FungiForest.py

Previously, exits which required day were just assumed to be okay, and night exits only required access to change time of day. I hoped this was sufficient, but it was not. Thus, a more complex time of day system has been added.
It basically works by each region having a dayAccess and nightAccess variable. When you start, the starting region is granted day access, and night access if the night switch has been reached since night persists across resets. Night access is also granted to the forest start region when the night switch is reached there.
When an exit is checked, the source region will transfer its dayAccess status to the destination unless the exit is night-only, and vice versa. This causes the time access variables to propagate across the world graph, but be stopped at exits …

Update time of day logic

---

ui/rando_options.py

If Unlock_All_Moves is off and Level_order_rando is on, force Shuffle_moves to be on.

Prevent some UI options for likely fill failures

---

randomizer/LogicFiles/Shops.py

Previously, logic assumed that if items weren't being shuffled, you could buy any item from the same type of shop as long as you'd been up to the right level (the same way the levels work in vanilla) so if you went to Cranky in Castle you could buy any item from any Cranky in that shop. This PR corrects this, since in actuality the items are still restricted to their respective levels.

Don't assume items can be bought from other shops when items unshuffled

---

GenTracker.py
TrackerTemplate.html
randomizer/Patching/ApplyRandomizer.py
templates/settings.html.jinja2

Adds a simple HTML tracker for item locations and entrances. It uses an HTML template with some generated tables based on the spoiler, and can be downloaded from the site alongside the spoiler. The tracker is shown in the image below. The "answers" to each location and exit are "spoilered" by being hidden, unless you mouse over them, or check that row's checkbox. When you check the checkbox, that row will stay unhidden. The tracker also updates a "state" text field which keeps track of which checkboxes are checked. (The state string is just a base64 encoding of a json). If you save this string between sessions, you can put it back into the state box and hit "Load State" to load all the checkboxes you checked in your previous session.
For the CSS of the page, I copied values for colors, …

Add simple html spoiler tracker

---

randomizer/Patching/EnemyRando.py
static/presets/2dos_special.json
static/presets/coupled_lzr_balanced.json
static/presets/decoupled_lzr_balanced.json
static/presets/go_bananas.json
static/presets/hell.json
static/presets/level_order_balanced.json
static/presets/suggested.json
static/presets/vanillaesque.json
templates/rando_options.html.jinja2

Splits off crown enemy randomizing and enemy speed randomizing from the base enemy type randomizing.
Open to suggestions on the preset edits. I left them unchanged from live site behavior.

Split off crown and speed randomizers

---

randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/LogicFiles/JungleJapes.py
randomizer/Settings.py
randomizer/Spoiler.py
static/presets/2dos_special.json
static/presets/coupled_lzr_balanced.json
static/presets/decoupled_lzr_balanced.json
static/presets/go_bananas.json
static/presets/hell.json
static/presets/level_order_balanced.json
static/presets/suggested.json
static/presets/vanillaesque.json
templates/overworld.html.jinja2

Still needs flags to be set in rom when setting is turned on.
Adds an "Open Levels" setting in the GUI and adjusts logic when the setting is enabled according to #421 
Note this does not include the gates in the first cave of Jungle Japes, or the gate to the Cannonball area in Gloomy Galleon.
The one logic this applies to that isn't a transition is the banana in the power hut since it pre-sets main core activated.

Add setting and logic for open levels

---

randomizer/Fill.py
randomizer/Lists/Item.py
randomizer/LogicClasses.py
randomizer/Spoiler.py

This adds the logically available GB count to each sphere. It does this by adding GBs as a playthrough location, but does not actually add it to the playthrough. 
I refactored Spheres as a logic class. In the future this could maybe track additional helpful info about spheres like maybe blueprints or coin counts.
It is possible to add the exact expected GBs to the playthrough, but as-is this adds several minutes to `ParePlaythrough()` to get rid of the excess, settings dependent. We could probably speed up the culling of GB locations but I didn't look into yet.
My python's a little rusty, so that bit in `Spoiler.py` could probably be more python-y somehow?

Add Available GB Count to each sphere

---

randomizer/Fill.py

An addition to having the available GB count on the sphere, this update also adds the "logically required" GBs to the spoiler. I skipped this in the original commit because it added a ton of time to paring the playthrough. With some tricks, we can cut down on that dramatically. 
A "logically required" GB is any GB that can be obtained in a sphere with a smaller available GB count than the largest B Locker requirement (usually Helm, but some maniacs might not make it that). This concept lets us very quickly cull GBs that aren't required.
Where these changes work best is early in level order randomizer seeds where the logic can sometimes require you to get every GB available. Knowing that you needed all 5 GBs isn't very helpful, but being given the locations in the spoiler can be very …

Add Individual GBs to the Spoiler

---

randomizer/Fill.py
randomizer/Settings.py
randomizer/Spoiler.py
templates/rando_options.html.jinja2

Implements #516 
Adds a "No Logic" toggle at the top of global settings, cfox may want to move this elsewhere but that place made sense to me. The tooltips warns the user that it can lead to unbeatable seeds.
Adding no logic required changing only a couple things:
* Telling both world verification functions to always return true if it's on (World is always valid!)
* Tell the PlaceItems function to always use random fill if it's on
This also necessitated changing RandomFill to handle whenever validLocations is a dictionary since it hadn't been upgraded for that yet.

Add no logic toggle

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Settings.py
randomizer/ShuffleExits.py

The culmination of a lot of anger at moves failing to place for no good reason. I suspect there might still be an underlying reason in the code somewhere but that's besides the point.
Level order shuffling previously placed items in this order:
(shared moves) -> (kongs) -> (remaining moves)
This PR changes this it to this order:
(kongs) -> (moves that unlock kongs) -> (shared moves) -> (remaining moves)
To better facilitate the shuffling some new methods have been created, most notably a method that never* fails to place Kongs.
*if the level order shuffler correctly follows logic

Priority Move Placing

---

ui/rando_options.py

If level order rando was cached when you refresh it wouldn't disable the toggles correctly.

Fixed small flaw in UI disable logic.

---

randomizer/Fill.py
randomizer/ShuffleExits.py

This PR should greatly improve the success rate of seeds that have a very early Caves. It priority places moves that grant access to a Caves T&S if it shows up early enough.
Other fixes include
- Fixing Caves level possibilities in starts with one kong
- More logic flexibility in open levels
- Prevented an unfathomably rare seed brick with Lanky's cage

The Caves Issue

---

randomizer/Fill.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/ShuffleExits.py

Two parts:
1. Removing the extra logic added for Caves now that there's a T&S available for everyone
2. Bypassing a coin logic check for priority items. It's explained in the code, but the idea is that there's only a handful of priority moves to place, so we can skip the coin check and let the coin logic sort itself out later. This check was bricking every one kong LO start because the priority move placement blocked access to later levels, making the coin count inaccurate to begin with.

Fix one kong LO starts and remove unneeded Caves logic

---

randomizer/Fill.py
randomizer/Settings.py

Fixes an issue where some items wouldn't be placed in No Logic seeds. 
This PR also gives the ability for No Logic seeds to unlock Kongs, guaranteeing they won't lock each other.
It also fixes an issue where a non-diddy/chunky Kong could be assigned to unlock Tiny in entrance shuffle modes.

No Logic Item Placement Fixes

---

base-hack/src/misc/object_instance_script_changes.c

This fixes an error where the script was not checking if the ```fast_gbs``` setting was on before disabling all the doors. This has been tested and verified to work with the setting both on and off.

Diddy fast RD fix

---

randomizer/Settings.py

This would crash on settings that didn't require the Rareware Coin

fix issue with None medal requirement

---

randomizer/Patching/ApplyRandomizer.py
randomizer/Spoiler.py

Used Medal Text box even when RW coin wasn't required. Now defaults to 15.

Fixed Default Banana Medal requirement.

---

randomizer/Enums/Regions.py
randomizer/Fill.py
randomizer/Lists/Warps.py
randomizer/LogicFiles/CrystalCaves.py

Creates a new Region for the bananaport on the Caves spire. In shuffled + activated warps, this warp could be the only access to some colored bananas or GBs, which could be extremely annoying to get if T&S or B. Locker rolls high. Giving it its own region effectively locks the warp behind jetpack.

created new region for bp on caves spire

---

randomizer/Fill.py
randomizer/Lists/KasplatLocations.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/JungleJapes.py

This PR removes the unnecessary kong checks on some vine-locked areas like upper Isles. This should cut down on seed generation failure when your starting Kongs don't have access to level 2.

Removing vine logic

---

randomizer/Patching/ShopRandomizer.py

Because no Isles shops are shuffled in LZR, the shop randomizer key errored when trying to find Isles shops.

fixed lzr + shop rando bug

---

randomizer/Fill.py
randomizer/Lists/KasplatLocations.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/FungiForest.py
randomizer/ShuffleKasplats.py

Fixed major issue where kasplat logic was incorrect. Either too many kasplats would be available or not enough kasplats would be available logically.
The minor fixes:
- That Tiny barrel in Caves is now marked correctly as a Tiny barrel.
- Fixed logic for getting from the worm area to main (they're not one-way gates). This shouldn't change anything, as you could have just deathwarped anyway.
- Shuffling the kongs before picking kasplat locations *should* increase location diversity.

fixed kasplat location logic and other minor fixes

---

randomizer/ShuffleBosses.py

Two parts:
- Adding Kongs to level order rando boss pools - Tiny to Dillo 2 and DK to Pufftoss
- Fixing vanilla-esque boss shuffling options ( #540 ). Most of these won't be relevant to the average user as Kong rando must be off and Level Order rando requires Kong rando to be on.

Fix vanilla boss shuffles and LO kong pools

---

randomizer/Fill.py
randomizer/Lists/Warps.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/Settings.py
randomizer/ShuffleExits.py
randomizer/ShuffleWarps.py
randomizer/Spoiler.py

The main thrust of this PR is to convert Kong item placement to using the GetItemPrerequisites method I made the other day for move placement. Now the fill can dynamically assess what moves are needing priority placement, going so far as to even be able to place Diddy in the Llama temple in some settings. The idea behind this was to create more flexibility in how items are placed, eventually leading up to placing Kongs on moves someday. This is the first step in that process.
The last major issue is the bananaports shuffle not being correctly written to the ROM, and this PR locks a couple warps to ensure that all seeds are beatable until we resolve that issue.
Other smaller issues resolved:
- Adding logical access to the Caves boss from the T&S we placed (should save some false fill …

Genericize Kong Dependencies

---

randomizer/ShuffleExits.py
templates/rando_options.html.jinja2
ui/rando_options.py

I think this prevents the issue found in #484 
I suspect there's an underlying issue here, as attempts to loop the Castle minecart failed correctly. In any case this fix should prevent Japes or Forest minecarts from looping themselves and making seeds un-101%-able
Also adds extreme price option with no logic.

Minecart exit loop fix

---

randomizer/Fill.py
randomizer/Logic.py
randomizer/Settings.py
randomizer/ShuffleBosses.py
randomizer/ShuffleExits.py
static/presets/2dos_special.json
static/presets/cfox_luck.json
static/presets/coupled_lzr_balanced.json
static/presets/decoupled_lzr_balanced.json
static/presets/default.json
static/presets/hell.json
static/presets/season1.json
static/presets/suggested.json
templates/difficulty.html.jinja2
ui/rando_options.py

Adds a "hard level progression" option that removes the two main restrictions of the existing level order randomizer:
- The logic no longer cares about collecting keys in order
- The logic no longer cares about how many Kongs you have ever
This means that you may have to return to levels later to beat the bosses because future levels have moves or Kongs you need to get more CBs or beat the boss itself. GB requirements for B. Lockers may vary wildly, burying Kongs deep into seeds.
It needs playtesting to fine-tune some of the guesses I made when adjusting B. Lockers and Troff n Scoffs.

Hard Level Progression

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py
randomizer/Lists/Location.py
randomizer/Lists/WrinklyHints.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Patching/UpdateHints.py
randomizer/Settings.py

Major hint rework:
- Moved hint generation into `Fill.py`. This enables better use of logic and debugging to produce higher quality hints
- Improved hint location placement in order to reduce bad hints
- Removed static hint distribution in favor of variance w/ minimum requirements depending on the settings. The minimums are pretty high so it shouldn't feel dramatically different. A future implementation might remove minimums and weight the random choice instead?
- Buffed many hints directly or indirectly:
-- Kong location hints also now hint the freeing kong and can only be found on doors for that freeing kong
-- Single move hints always hint Way of the Hoard hints (which are now removed)
-- Entrance hints now only hint useful zones with limited entrances but valuable contents (kongs, …

Hint Rework

---

randomizer/CompileHints.py
randomizer/Settings.py

Feedback and bug fixes:
- Helm GB count is no longer hinted when the Helm value is known (maximized or preset)
- Shortened the phrasing on some hints so you don't accidentally miss key info
- Loosened the placement requirement on Kong location hints. It now only guarantees that the hint is placed on a free kong's door, not the freeing kong's door. This should help give routing hints such as "oh this locked kong unlocks another kong!"
- Removed Helm order hints when helm is skipped
- Prevented the same B. Locker from being hinted twice in the same lobby (was particularly bad in Level 6/7)
- Set a default for `owned_kongs_by_level` and `owned_moves_by_level` (hopefully whatever the hell Killi is cooking up works now)

Day 1 Hint Rework Feedback

---

randomizer/CompileHints.py
randomizer/Fill.py

- No more shop hints on vanilla move locations
- Level order no longer matters on No Logic
- Fixed issue where WotH could have an extra unnecessary item

More hint fixes

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/ShuffleExits.py

Another rework to hint move locations, this time to better cover 5 kong starts and potential ties in B. Lockers.
Fixes some bugs:
- Changes how hints are skipped when no more locations are available to avoid a bad reference bug
- Prevent B. Lockers from being out of order in standard level order rando. This usually manifested as a level 4 being cheaper than a level 3.

hint move location edge cases

---

randomizer/Fill.py
randomizer/Spoiler.py
templates/difficulty.html.jinja2
templates/rando_options.html.jinja2

Sometimes on hard level progression seed gen it wouldn't reduce B. Lockers when the value was above the settings-specified percentage of maximum available GBs, leading to insanely hard seeds without Hard B. Lockers active.

prevent psychotically difficulty seeds unless requested

---

randomizer/Patching/EnemyRando.py

Removes the possibility for multiple GetOuts to spawn in 1 crown battle on Hard difficulty. 
GetOuts now properly have a ~1/156 chance per enemy to spawn, down from ~9/156 (but max 1 per battle, ofcourse)

fixed double getout and too-common getout

---

randomizer/CompileHints.py

Based on feedback, a very light touch to the hint distribution.
It sounds like putting a hint "on the path" is making them appear very often, so we don't need as many helm order hints.
Pulling one off move locations. This is intended to increase the variance a little bit, as it will be redistributed randomly among the possible hints.
Also added a few more joke hints.

Hint distro tweak

---

randomizer/Patching/ShopRandomizer.py

Fixes the following
> MadagascarDave — Today at 4:10 AM
> so I had a shop shuffle problem in caves. Candy shop at Cranky spot. I could get through the door with Tiny and Diddy but Chunky and DK wouldn't go in. I ended up going in with the smaller kong and switching just as I entered to progress, but I know quick swap isn't supposed to be logic

Adjust shop scales

---

randomizer/Fill.py

In the current flow `ParePlaythrough` pares one slam and then `PareWoth` pares the other, so no slams make it to the way of the hoard in the spoiler log (unless one is locked by the other - unfathomably rare) despite one of them being definitely required.

Add slams to woth

---

randomizer/CollectibleLogicFiles/AngryAztec.py
randomizer/Enums/Items.py
randomizer/Enums/MoveTypes.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Item.py
randomizer/Logic.py
randomizer/Patching/PriceRando.py
randomizer/Prices.py
randomizer/Settings.py
randomizer/Spoiler.py
templates/rando_options.html.jinja2

Adds logic for placing training barrel moves. Note these rules only apply to non-hard LO settings:
- You must have vines before Aztec or level 2 if you don't have Isles warps active
- You must have swim before level 4
- You must have barrels before level 2 to promote boss diversity
Hard mode ignores all this logic but does keep in mind lobby accessibility when generating progression.
Writing them to the ROM is in, but probably loaded with bugs. Proceed with caution.

Training and BFI Move Placement and Logic

---

randomizer/Lists/KasplatLocations.py
randomizer/Logic.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/JungleJapes.py

Adds orange requirement for hard-required cabins + anthill and also shellhive.
Also fixed galleon lobby -> isles entrance logic.

Orange Logic

---

randomizer/Fill.py
randomizer/Lists/Warps.py
randomizer/ShuffleWarps.py

Adds transitions for activated cross-map warps. Does take into consideration having only Isles warps active

Activated cross-map warp logic

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Logic.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FungiForest.py
randomizer/Settings.py
randomizer/ShuffleItems.py
randomizer/ShuffleKasplats.py

Adds `settings.shuffled_location_types` to the settings which enables a proper refactor of Fill. Now we're not beholden to checking specific presets like "phase1". 
This PR refactors the fill methods to unify the logic they flow through. Now all code flows go through `Fill()` and can selectively fill items depending on the shuffled location types. This is the precursor to a customizable item pool shuffling.

Fill Unity Refactor

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Item.py
randomizer/Lists/Location.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Patching/MoveLocationRando.py
randomizer/Settings.py
randomizer/ShuffleDoors.py
randomizer/ShuffleItems.py
randomizer/ShuffleKasplats.py
randomizer/Spoiler.py
templates/overworld.html.jinja2

This PR fixes the conversion from the logic's `LocationList` to the patcher's `item_placement`
A couple other bugs found and ironed out on the way - most notable among them is the spoiler json now being generated inside the logic loop. Anything wanting to be placed in the spoiler log needs to be determined before the seed is finished generating. May revisit this if certain things are desired. This is done so adjustments to `LocationList` (kasplat rando locations foremost) can have their placed items shown in the spoiler.

Last major item shuffler fixes

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Location.py
randomizer/Logic.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Settings.py
randomizer/Spoiler.py
static/presets/2dos_special.json
static/presets/cfox_luck.json
static/presets/coupled_lzr_balanced.json
static/presets/decoupled_lzr_balanced.json
static/presets/default.json
static/presets/hell.json
static/presets/qol_only.json
static/presets/season1.json
static/presets/suggested.json
templates/overworld.html.jinja2
templates/rando_options.html.jinja2
ui/__init__.py
ui/generate_buttons.py
ui/rando_options.py

Fixed unlock all moves not generating correctly.
Updated the UI to lock out some mutually exclusive settings.
Shockwave is now included in "Unlock All Moves"
Moved unlock shockwave toggle to the dropdown for BFI's status

fixed unlock all moves, moved starting shockwave

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/LogicFiles/DKIsles.py
randomizer/Settings.py
randomizer/Spoiler.py

Improved hints for item rando:
- Converted shop hints to a new type that better handles all items being in shops
- Converted move location hints to Way of the Hoard location hints that tell you a specific location is on the Way of the Hoard
Minor logic fixes as well:
- Fixed issue with no logic having incorrect progression
- Tiny's GB in Galleon lobby now requires swim

better item rando hints

---

randomizer/Lists/DoorLocations.py

- Aztec: Lobby - Pillar Wall, the Z coordinate is now different from the X coordinate
- Creepy Castle Near Candy's and Near Funky's are now on the correct map.

fix door locations

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py
randomizer/Prices.py
randomizer/Settings.py
randomizer/Spoiler.py
tests/test_spoiler.py

- Vanilla prices are fixed
- A couple issues with non-item rando hints are fixed including bad WotH errors and shop dumps not working. The latter was fixed by axing the old hint category and just using the new shop dump hints
- An issue with duplicate code messing up kong calculations for the complex shuffler that made me question how it ever worked recently at all
BIG ADDITION is the debug file update that should make it a lot easier to debug settings

catching up on known issues

---

randomizer/CompileHints.py
randomizer/Enums/Events.py
randomizer/Enums/Regions.py
randomizer/Fill.py
randomizer/Logic.py
randomizer/LogicFiles/DKIsles.py
tests/test_spoiler.py

Fixed foolish hints:
- Foolish moves are now moves that do not lock any other moves (even if they are foolish)
- Foolish region hints are now correct and point at regions with no major items (they can contain foolish moves)
Fixed WotH hints:
- If key 8 is locked in helm, that location cannot be hinted
Fixed Path hints:
- Removed moves from WotH that are only needed for coins
- A consequence of the above change is that **moves required for minigames are now in the path**
- You can now see a WotH for the Banana Hoard (your win condition)
Rework of win condition logic:
- New "Credits" region that houses the Banana Hoard. Meeting your win condition will give you access to this location

reworked foolish hints to match definitions

---

randomizer/CompileHints.py
randomizer/Enums/Regions.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Logic.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py

This PR tackles a couple major logic issues:
- Refactors priority placement to be independent of placing kong prerequisites. This allows arbitrary priority placing, which is now applied to critical training barrel moves. This (combined with a side effects fix) should dramatically reduce fill fail errors.
- Fixes an issue where logic often couldn't find your training barrel moves in LZR. This is achieved with a "Game Start" region that will always be where the logic starts.
Misc fixes:
- Implements some feedback on hint region names
- Prevent Helm Key from being on the path of key 8 if it's locked there
- No longer generating paths for seeds that don't need them, should be a minor time save

Priority Place Refactor

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/Item.py
randomizer/Logic.py
randomizer/LogicFiles/JungleJapes.py
randomizer/Settings.py
randomizer/ShuffleExits.py

Implements a more generic kong placement strategy that will work with kongs in the larger item rando location pool.
Other fixes:
- If Barrels was WotH your paths could be seriously wrong, this is now fixed
- Remembered you can use your instrument in the shellhive
- Hopefully fixed weird error with placed moves not being found in a list of all moves
- Set up placeholder for kong path hints when they're in the pool

Kongs on Items Logic

---

randomizer/LogicFiles/HideoutHelm.py

This fixes an issue where helm rooms are assumed to have every instrument spawned from the start when using the "skip start" helm setting (internally named "skip_start"), even when the B.o.M is active (1-5 rooms required to be completed first).

fix helm logic for "skip_start"

---

randomizer/Fill.py
randomizer/Logic.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/DKIsles.py
randomizer/Spoiler.py

Fixed an issue where vines was incorrectly woth
A consequence of this change is that vines and swim will now appear on paths again, but only in regards to prerequisites beyond level entry.

fix vines woth being incorrect

---

randomizer/ShuffleDoors.py

Fixes a bug where vanilla wrinkly doors would fail to exist if Wrinkly Location rando is off, TnS Portal Location rando is on and the Remove Wrinkly Puzzles QoL feature is enabled.

door location rando bug fix

---

randomizer/Lists/CBLocations/AngryAztecCBLocations.py
randomizer/Lists/CBLocations/CreepyCastleCBLocations.py
randomizer/Lists/CBLocations/CrystalCavesCBLocations.py
randomizer/Lists/CBLocations/FranticFactoryCBLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CBLocations/GloomyGalleonCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py
randomizer/LogicFiles/FungiForest.py
randomizer/Patching/EnemyRando.py

-Made sure one-time-only enemies in Castle's Library and Museum are not required for Kremling Kapture
-Re-introduced enemy rando to Tiny's room in tiny temple, if at least 1 suitable enemy type is selected. (same goes for Library and Ball Room)
-Added instrument to Fungi Anthill logic
-Shifted an out of bounds CB bunch back into bounds
-Temporarily disabled the CB bunches in Japes' cage until access to them can be guaranteed
-A few CB name changes for readability
-A stray typo fix or two

Kremlin kapture korrection and minor bug fixes

---

randomizer/CompileHints.py
templates/base.html.jinja2
templates/cosmetics.html.jinja2
templates/difficulty.html.jinja2
templates/frontpage.html.jinja2
templates/getting_started.html.jinja2
templates/macros.html.jinja2
templates/nav-tabs.html.jinja2
templates/overworld.html.jinja2
templates/settings.html.jinja2
tests/test_spoiler.py

The number of path hints per key you get is now based on how long the path is to that Key. This should cut down on useless hints, particularly when keys are in shops, and give extra help when most needed on long dependency chains.
Some other lint-related changes in here in the jinja.

Dynamic Path Hint Quantity

---

randomizer/CollectibleLogicFiles/CreepyCastle.py
randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py
randomizer/Logic.py

Finally implements hints for Kong items in item rando. Each kong is hinted once with the freeing kong and level. It should put the hint in or before the level the Kong is in. It's a pretty lazy implementation of hint door choice but that's mainly because the hint door logic rework is coming.
Other minor fixes:
- Camera path hints now follow the same rules as path hints for keys
- Homing and Sniper are merged when considering foolishness
- Quick cb logic fix in Castle

Kong Item Rando Hints

---

.vscode/tasks.json
randomizer/Fill.py
randomizer/Lists/Warps.py
randomizer/Logic.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/FungiForest.py

-Fixed a bug where Vines would be required for reaching the Aztec Lobby, regardless of pre-activated Isles warps
-Fixed a bug where part of the "Forest Center and Beanstalk" was incorrectly named "Beanstalk Area" 
-Fixed a bug where too many kong-freeing moves were logically required in order to get the kong-freeing reward from an empty cage

Logic fixes

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/Location.py
randomizer/LogicFiles/Shops.py
randomizer/Prices.py
randomizer/Settings.py
templates/difficulty.html.jinja2
tests/test_spoiler.py
ui/__init__.py
ui/rando_options.py

Adds a new setting "Smaller Shops" that randomly removes two kong locations from each shop. The kong locations removed are distributed evenly across kongs so all kongs have the same number of shop locations available.
Other fixes:
- Fixed one bad shop logic
- Fixed a possible issue where unplacing an item during the assumed fill might have to unplace other items
- Shockwave can no longer be hinted foolish so Keiper stops bullying me
- Medals are foolish hints have been upgraded into "colored bananas are foolish" hints by checking the corresponding boss location. The old medal region foolish hints are no longer found, which is to say you won't get a "medals are foolish" check, only colored bananas in an all-or-nothing way.
- Fixed obscenely rare case where hint generation would crash if a …

Smaller Shops Setting

---

base-hack/Build/model_port.py
randomizer/Fill.py
randomizer/LogicFiles/JungleJapes.py

- Changed complex key placement algorithm to Assumed. This led to a huge increase in available locations for keys to be placed. I suspect this will fix the feeling that keys are placed early and often in complex seeds.
- Added a tweak that should (on average) lower late B. Lockers in complex seeds without hard B. Lockers
- Fixed some bad logic on the Japes Mountain warp

Complex Fill Fixes

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/Item.py
randomizer/Lists/Location.py
randomizer/LogicClasses.py
randomizer/LogicFiles/FungiForest.py

- Fixed an issue with the rabbit race's region by making the glitch access an "auxiliary" location logic
- Slight name tweak to the Lanky GB instrument pad to differentiate it from the Lanky upper Isles rocketbarrel pad
- Fixed LZR + item rando issue

stray logic fixes and fill fixes

---

randomizer/Fill.py

- Shockwave can now be foolish with rainbow coins in the pool
- Fixed issues with foolish regions not counting shockwave as a major item
- It _should_ now consider vanilla camera/shockwave placement when considering the banana fairy's room as foolish

Shockwave foolish once more

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Location.py
randomizer/Logic.py
randomizer/Spoiler.py
tests/test_spoiler.py

Fix for the Pie Incident:
- Move placement needed to always assume GBs, Blueprints, Fairies, etc. (depending on what's in the item pool) in order to correctly place items
Other fixes here:
- Kongless hint doors now has no logic tied to it
- Moves you start with are now correctly hinted foolish if they are foolish. This only matters for items you start with besides the moves in the training barrels. Right now this is only useful for Camera & Shockwave but it could apply to other moves if we get around to some way to start with arbitrary moves.
- Put switch strength shuffle in the spoiler log

Fixing the Pie Incident

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/DoorLocations.py
randomizer/Logic.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/GloomyGalleon.py
tests/test_spoiler.py

- Removed Foolish move hints. I can't think of a reasonable way to get around the issues I bring up in comments. The code is all there if we want to resurrect it. As it stands, I can't guarantee that both sides of an either/or would be not foolish. Foolish move hints have been converted to more foolish region hints.
- Fixed an issue where the logic might expect you to get a slam for the item in Chunky's cage even when it's empty
- Converted K. Rool path hints to a "truer" path. It will now hint *anything* required to K. Rool. To compensate, you should see a greater number of these hints than before, up to 5 depending on the phases involved and the length of the path.
- Fixed some logic issues that would affect some (most?) random starting locations and would likely cause issues with LZR.

Sunset foolish moves, possibly fix LZR

---

randomizer/Fill.py

Turns out the Banana Hoard path was very important to key hints, woops. This might impact other win cons but I'm shooting first and asking questions later.

fixed issue preventing key hints from appearing

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/CBLocations/AngryAztecCBLocations.py
randomizer/Lists/CBLocations/CreepyCastleCBLocations.py
randomizer/Lists/CBLocations/CrystalCavesCBLocations.py
randomizer/Lists/CBLocations/FranticFactoryCBLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CBLocations/GloomyGalleonCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py
randomizer/Lists/Exceptions.py
randomizer/Lists/Location.py
randomizer/LogicClasses.py
randomizer/ShuffleBosses.py
randomizer/ShuffleCBs.py
tests/test_spoiler.py

The CB rando filler wouldn't always put 100 cbs for each kong in each level. Now it won't proceed until it has. Failure is relatively unlikely and the fill process is very fast, so I just slapped a retry loop on it until it came up with a valid combination.
Also fixed:
- Key 8 in Helm will get path hints even if keys aren't in the pool
- Adjusted the early key hints to match the "held by a kasplat" phrasing

fix 100cb fill fails, always path hint key 8

---

randomizer/Enums/Events.py
randomizer/Fill.py
randomizer/Logic.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/DKIsles.py

Couple things here:
- Split up pathmode into different assumptions. This should solve a couple problems and generally be more flexible. The specific issue I intended to resolve was giving LZR seeds good K. Rool paths.
- Fixed a recurring fill failure that occurred when barrels (or barrels locking items) were placed in Helm in simple level order.
- Fixed some logic with the Caves MP Igloo, mostly covering for when warps are active and shuffled in Caves.

split up pathmode, boss fill fix

---

randomizer/ShuffleWarps.py
ui/rando_options.py

- fixed the "Shuffled Bananaports" gear not being disabled by default when initially loading the page with "Vanilla" warps selected
- fixed a nigh-insignificant syntax oversight with "verifySelectedWarps()" where I forgot Python was a pass-by-assignment language

Shuffled Warps Minor Cleanup

---

randomizer/Fill.py
randomizer/ItemPool.py
tests/test_spoiler.py

The order of operations of the fill and the assumptions made during the fill got a bit out of whack, causing excessive (any amount is excessive to me) fill failures. 
To remedy this, this PR does the following:
- Trim and cut some debug code to avoid a possible crash if CB rando comes up with invalid CBs
- Create a generic method most PlaceItems methods will call to get the list of items to assume. This should help make it simpler to shuffle around item placement order.
- Rework assumptions for fairies and medals to always carefully place the number of those items that could logically lock something
- Place rainbow coins first and more carefully. I'm not certain this should help, but I think that assuming coins for too long could cause shops to fill up too fast?
All in all these changes …

Fill Reorganization

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Warps.py
randomizer/ShuffleWarps.py

Created warp lambda logics as a variable on the warp data class instead of being built as the locationlogics were created. This makes the logic actually respect the event logic.
Also changed kongs-outside-cages fills to assumed algo and cleaned up that flow. It wasn't assuming keys were owned too, which may have heavily impacted kong placement potential.

Fix Warp Lambdas

---

randomizer/Fill.py
randomizer/Lists/CrownLocations.py
randomizer/Lists/KasplatLocations.py
randomizer/LogicFiles/AngryAztec.py

- Foolish hints now take into account when you have something on specific checks. If you have a major item on Rareware GB, Jetpac, Mermaid, or Beanstalk, then Fairies, Medals, Pearls, and the Bean will not be foolish, respectively. This does loop on itself so if you have the bean on Mermaid and Ostand on the Beanstalk, neither the bean nor pearls will be in foolish regions. This means, for example, if you find a medal in a foolish region, then Jetpac is dead.
- Changed the logic around the Aztec stone door Kasplat (and the crown that's in there) to no longer logically allow a damage boost. This means it's now a DK/Tiny kasplat needing either Strong Kong or Twirl.
- Fixed an issue where Kong location hints could still say "Any Kong" because the locations weren't being updated if a Kong was …

Some fixes

---

randomizer/Enums/Settings.py
randomizer/SettingStrings.py

This PR handles negative numbers in the settings string by using two's complement negation.
It also changes a couple of settings from `int4` to `int8`. One of these was due to the loss of higher values, as a result of now including negative numbers. The other was an oversight.

Fixing settings string to handle negative numbers

---

randomizer/SettingStrings.py

A copy/paste error was preventing int lists from working correctly. That's now been fixed.
The decrypt function also converts values to enums where appropriate. This saves a step down the line, and adds another bit of validation to the settings string (if any enum values are invalid, an error will be thrown).

Fixing broken list decoding in settings strings

---

randomizer/Enums/Settings.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/DoorLocations.py
randomizer/Logic.py
randomizer/Settings.py
randomizer/ShuffleDoors.py
static/presets/default.json
templates/rando_options.html.jinja2
tests/test_spoiler.py
ui/__init__.py
ui/rando_options.py
wiki-lists/DOORS.MD

Added vanilla door shuffle per the requirements. If this setting is on, then it overrides your Wrinkly/T&S door rando setting.
https://docs.google.com/document/d/1XSr7MUVh29J4LLVZ2ECrRn1jgVpeAuRcDR764uZ3XIs/edit
Also included are some big fill fixes:
- Fixed logic around the Rareware GB and Coin locations (major fill fail reason)
- Moved Rainbow Coin placement to be even before Kongs and Moves (another likely major fill fail reason)
- Implemented some optimizations to the fill to hopefully speed things up (even though I had to slow one thing down)
- Foolish hints now respect helm doors (except for GBs)

Vanilla Door Shuffle

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/Location.py
randomizer/Logic.py
randomizer/Spoiler.py

Woops the > should have been a <, hint duplication aversion was not functional at all.
Other fixes
- Fixed an issue where training barrels that were supposed to be empty could still get items if you started with <4 moves.
- Fixed a boss fill issue when twirl or hunky was in Helm. They can no longer be in Helm in simple level order.

fix hint aversion, fix <4 starting move issue

---

randomizer/CompileHints.py
randomizer/Enums/Items.py
randomizer/Fill.py
randomizer/Lists/Location.py
randomizer/Spoiler.py

Updated the hint coloring to give each level its own color. This will apply to all non-cryptic hints as well as regions using their level's color. The colors chosen were my decision and are up for debate.
Fill fixes:
- Fixed an issue where starting with 5 kongs wasn't wiping progression, preventing any fills from succeeding.
- The fill no longer places keys you start with, simultaneously simplifying key placement. This should prevent nearly all empty locations when you have junk items on.
- Fixed an EXTREMELY rare issue where seed generation would softlock because it had too many required hints to place.
- The fill now allows checking exit level options if you start in a random location. Some spawn locations need this to not ruin hint paths.

Color-coding levels, fill fixes

---

randomizer/Fill.py
randomizer/Lists/Exceptions.py
randomizer/Lists/Location.py
randomizer/Settings.py
randomizer/ShuffleDoors.py
randomizer/ShuffleKasplats.py
randomizer/Spoiler.py

Reworked smaller shops and starting moves to use a new `inaccessible` variable on the Location object. This has a couple implications:
- Immediately, it fixes that one stupid error where it would try to delete a nonexistent location from LocationList
- THE BIG ONE: seed generation is once again idempotent. You can now make multiple seeds locally without restarting everything.
Other fixes:
- Removed coloring characters from the microhints in the spoiler log
- Fixed an issue where no logic would never succeed fills
- Fixed an issue where vanilla door rando could have that one japes alcove T&S still be a T&S when it shouldn't because the indicator doesn't appear on it

Inaccessibility Rework

---

randomizer/Enums/Settings.py

The settings enums were originally listed in the order they appeared on the website. Since the website's settings can be rearranged (and have been), the order no longer makes sense. They're now alphabetized, so they don't need to regularly change.
This change is a no-op.

Alphabetize settings enums

---

.vscode/tasks.json
randomizer/CompileHints.py
randomizer/Lists/CrownLocations.py
randomizer/Lists/Location.py
randomizer/Logic.py
wiki-lists/CROWNS.MD

- Fixed an issue where Kongs/keys could be placed in too-late levels depending on the keys you start with
- Removed a problematic crown location from castle library
- Allow K. Rool/Helm order hints to appear if the number of phases/rooms is random and rolls 5
- Rename Kong cage locations to improve hint readability
- Improved Kremling Kapture hints - you now get path hints to the camera and the win condition is changed to K. Rool + camera

starting key issue fix, better snap win con

---

static/js/initalize.js

The music-loading function in initialize.js had an async-related issue where the filename was not preserved when loading in custom music files. This has been fixed by creating new Promises that store the filename in a separate variable upon creation.
The function now also uses `Promise.all` to ensure that there is no chance of a race condition unlinking files from filenames.

Fixing a bug with filenames for custom music

---

randomizer/CollectibleLogicFiles/CreepyCastle.py
randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/Location.py
randomizer/Logic.py
randomizer/LogicFiles/DKIsles.py
randomizer/Spoiler.py
tests/test_spoiler.py

- Actually fixed the issue where keys would be placed beyond they were logically required for
- Added the appropriate phase to K. Rool hints. The hints are generated in an identical manner, just with a little extra info to help you determine what exactly you're looking for.
- Added ability to plug a settings string into the python tests to debug them SIGNIFICANTLY easier than before.
- Fixed a couple stray logic issues - a bad transition in Isles and bad logic for CBs in the Library

Krool hint phases, Fix bad keys, Settings string test

---

randomizer/Fill.py
randomizer/LogicClasses.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
randomizer/Settings.py
randomizer/ShuffleDoors.py
randomizer/ShuffleShopLocations.py
randomizer/ShuffleWarps.py
randomizer/Spoiler.py
static/presets/qol_only.json
tests/test_spoiler.py

This PR attempts to solve some issues with local generation. It should be able to generate locally multiple times in a row now with some more settings on. Maybe this is the end of it? I dunno but it's better.
Other fixes:
- Fixed some starting locations starting you in the wrong region
- Improve the tests further by putting in the S2 preset and make it easier to work with. Also they pass now.
- Every 5th fail the fill will choose a new random starting location in case we found a bad one

better local resets, random starting location fixes

---

randomizer/CompileHints.py
randomizer/Enums/Settings.py
randomizer/Fill.py
randomizer/Lists/Patches.py
randomizer/Patching/ApplyRandomizer.py
templates/qualityoflife.html.jinja2
tests/test_spoiler.py
wiki-lists/PATCHES.MD

Added the fixed racing hints option. This preset is optimized specifically for the S2 racing preset and is very likely to throw errors on settings that deviate too much from it. The UI has messages that reflect this, so in my mind it's "buyer beware."
Other fixes:
- Fixed that one Fungi cannon boulder dirt patch again, but properly this time.

Racing hints

---

randomizer/CompileHints.py
randomizer/Logic.py
randomizer/ShuffleKasplats.py
randomizer/Spoiler.py
tests/test_spoiler.py

Improved foolish hints:
The regions hinted by foolish hints are now weighted by the size of the region. Eligible regions with more relevant checks are more likely to be hinted foolish.
Training move logic change:
You are now able to find vines, swim, and barrels BEFORE level 4. As before, you are able to find Tiny+Twirl OR vines before Aztec. These are now the only two fill rules for training moves.
In other fixes:
- Fixed an outrageously rare fill that could cause failures in boss fills
- Removed duplicate names from the item pool in the spoiler log. There can be only one Bean.

Improve foolish hints, Training logic alignment

---

randomizer/Enums/SearchMode.py
randomizer/Fill.py
randomizer/Lists/Location.py
randomizer/Logic.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/Prices.py
randomizer/Settings.py

Two major improvements to coin logic:
- When in the process of filling items, GetAccessibleLocations will now purchase empty locations. This should cut down on coin logic failures during fills, as a more accurate number of shop locations accessible will be returned.
- VerifyWorldWithWorstCoinUsage performance is GREATLY improved with some corner-cutting and optimization. I estimate this method is multiple times faster than it was before by significantly reducing the number of GetAccessibleLocations calls.
I estimate this PR is of higher risk than the average in less measurable metrics. My testing found you ran into almost zero coin locks on medium prices and a few coin locks on high prices. The big problem is that the odds of coin locks vary wildly by settings so I can't really guarantee …

Coin Logic Improvements

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/LogicFiles/JungleJapes.py
templates/rando_options.html.jinja2
tests/test_spoiler.py

- Removed duplicate progressive moves when selecting starting moves if you start with a low number of moves. This should generally reduce the number of times you load up on instrument upgrades or ammo belts as starting moves. You can still get them, they're just less likely
- Reduced the number of entrance hints in the default distribution
- Renamed Japes Highlands to Japes Hillside
- Fixed a bad UI tooltip

minor fill tweaks

---

randomizer/Settings.py

Fixed a bug where Key 8 is placed twice when selecting starting keys, not selecting key 8 as a starting key, and putting key 8 in helm. (A logical choice of settings, just the code being derpy. We still love the code)

Key 9 doesn't exist, it can't hurt you

---

.gitignore
randomizer/CompileHints.py
randomizer/Enums/Locations.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Location.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/Prices.py
randomizer/Settings.py
randomizer/ShuffleBosses.py
randomizer/ShuffleDoors.py
randomizer/ShuffleFairies.py
randomizer/ShuffleKasplats.py
tests/test_spoiler.py

- Added some logic to clear custom logic ahead of custom locations. This was intended to make sequential seed generations to be independent and it works... if the settings are identical. More to be done on this front but these changes don't really hurt any and are a good failsafe. The hint door shuffle change in particular definitely needed to happen.
- Improved Training move hints - you can no longer be hinted very obvious training moves on paths (e.g. Your training in Rocketbarrel is on the path to Diddy K. Rool or Your training in Vines is on the path to Key 8 (in helm).)
- Fixed an issue that would prevent certain random starting locations from generating because they couldn't logically pause exit.
- Fixed a potential LZR issue with FTA in Lanky's 2-door ship.
- Big update to the …

fixes to clear logic ahead of fills, training hint improvements, stray fixes

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Location.py
randomizer/LogicFiles/DKIsles.py
randomizer/Prices.py
randomizer/Settings.py
tests/test_spoiler.py

- Added a limit to the number of shared shops that can be filled in a seed. The limit is lowered slightly in an attempt to get around Helm problems that I plan on addressing later. The S2 limit is 11 (I don't think anyone has gotten close ever). Kamerson's settings that inspired all this is 7. This number takes into account smaller shops. When the Helm problems are addressed, these numbers may go up by 1, TBD.
- Renamed the "DK Isle" hint region to "Outside DK Isle" to distinguish it from the level "DK Isles"
- Fixed an issue where moves beyond 4 were ineligible for the un-hinting of training moves in my last update
- Added advanced logic transition from Cabin Isle to Upper Isles w/ twirl

limit shared shops, stray fixes

---

randomizer/Fill.py
randomizer/Lists/KasplatLocations.py
randomizer/Lists/Location.py
randomizer/Settings.py
randomizer/ShufflePatches.py
tests/test_spoiler.py
wiki-lists/KASPLATS.MD

- Nearly every Kasplat name has been shortened to better accommodate their text in hint windows. This comes in the form of removing grammatical frivolities in favor of delivering as much information as possible in fewer words. The one noteworthy change is "Galleon Kasplat: Near the Troff 'n' Scoff near Cranky's" -> "Galleon Kasplat: Past Vines"
- Dirt patch location names have been slightly shortened by removing "patch"
- The fill now logically places 1.2x the required number of medals/fairies before you can logically access the Rareware Coin/Rareware GB checks respectively. Relevant to Season 2, you will now have at least 6 fairies logically accessible before the Rareware GB check.
- The playthrough will now contain items relevant for your Helm doors more consistently.

Shorten Kasplat Names, better fill

---

randomizer/CollectibleLogicFiles/CrystalCaves.py
randomizer/LogicFiles/FungiForest.py

- Fixes a bug where the vanilla banana bunch in Diddy's Lower Cabin in Caves logically requires (rocketbarrel or advanced platforming) to obtain, specifically when CB Rando is disabled. Thanks Spikevegeta for finding this one
- Fixes a potential Random Starting Location bug
- Added skew into logic for the transition from Mushroom Area to Owl Tree Area

stray fixes

---

randomizer/Enums/Regions.py
randomizer/Lists/FairyLocations.py
randomizer/Lists/MapsAndExits.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/GloomyGalleon.py
wiki-lists/FAIRIES.MD

Some LZR logic fixes discovered yesterday:
- Added better glitch transitions between rooms in the galleon 5 door ship
- Removed a crappy technically possible glitch transition into the back of the llama temple
- Fixed an issue where Caves Lobby could be way too accessible
- It turns out the thornvine barn fairy requires DK to open the box
- Fixed a potential problem with the 2 door ship and not having High Requirements on

lzr logic fixes

---

randomizer/CompileHints.py
randomizer/Fill.py

- Reordered hint generation in such a way as to prevent joke hints from sneaking into S2 seeds.
- Prevented hint errors in settings with loads of starting moves.
- Added a small section at the start of hint gen to kick out seeds that may have accidentally enabled Fixed hints. It won't catch everything, but we can add things as we go. There are more known cases than this one, but they don't consistently error as much as alternative win conditions.

fix some edge cases in hints

---

randomizer/Logic.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/JungleJapes.py

- Cannon skew now correctly requires oranges (and non-ohko settings)
- Both gun skew and cannon skew are now logically considered in Jungle Japes
- Removed Isles skew due to a potential edge case with bananaport rando

Exskewse me?

---

randomizer/CompileHints.py

Very lightly locked keys weren't being hinted in Standard hint settings. Woops.

honey i broke the key hints again

---

generate_rando_ui.py
randomizer/Lists/Plandomizer.py
templates/plandomizer/plandomizer_general.html.jinja2
templates/plandomizer/plandomizer_hints.html.jinja2
templates/plandomizer/plandomizer_shops.html.jinja2
ui/plando_validation.py

- The "Starting Moves" selector has been removed, as it will be part of the non-plando randomizer.
- Hideout Helm has been rearranged so all of the medals are part of one group.
- Both Shops and Hints are now arranged by level, instead of by Kong. Across the entire plandomizer UI, levels are now the top-level grouping, followed by Kong. We should keep this consistent in the future.
- The Jetpac game no longer has a price field. It is still on the Shops tab.
- Internally, shop locations are no longer grouped separately from non-shop locations.
- An error with hint text validation has been fixed. (Regex is hard.)

Plandomizer UI updates (June 2023)

---

randomizer/Patching/ApplyLocal.py
randomizer/Settings.py

- Cosmetic seed is now explicitly defined by rando rather than being set to None. Additionally, cosmetic seed is now dumped to spoiler
- Crowns are now banned from being on the Helm Key location

Dump cosmetic seed

---

generate_rando_ui.py
randomizer/CompileHints.py
randomizer/Enums/Items.py
randomizer/Enums/Settings.py
randomizer/Fill.py
randomizer/Lists/Item.py
randomizer/SettingStrings.py
randomizer/Settings.py
templates/rando_options.html.jinja2
ui/__init__.py
ui/generate_buttons.py
ui/rando_options.py
wiki-lists/CUSTOM_LOCATIONS.MD

Added a starting move selector. You can pick any number of moves in the modal and one of the following will happen:
- If the number of selected moves matches the number of starting moves, you start with those moves
- If the number of selected moves is less than the number of starting moves, you start with the selected moves and random moves to reach the appropriate number of starting moves
- If the number of selected moves is greater than the number of starting moves, you start with a random selection of the selected moves up to the appropriate number of starting moves
Also some small hint fixes:
- Fixed an issue where the Bean would never have any point value
- Added Bean to Vials spoilers
- Taught Wrinkly how to count keys in order

Choose Starting Moves

---

randomizer/Lists/CBLocations/FranticFactoryCBLocations.py
randomizer/Prices.py
ui/rando_options.py
wiki-lists/COLORED_BANANAS.MD
wiki-lists/CUSTOM_LOCATIONS.MD

- Fixed a bug preventing seeds from generating if 3 slams were placed in shops
- Fixed a bug where seeds with vanilla prices wouldn't generate if Start with Simian Slam was disabled
- Fixed logic for the custom balloon location in Chunky's R&D room
- Fixed a UI bug where it was possible to select vanilla move locations and choose not to start with Simian Slam

minor bug fixes

---

randomizer/Lists/CustomLocations.py

Ban Melon Crates to spawn under R&D grates due to bounciness

Ban R&D Crates

---

randomizer/Lists/CBLocations/GloomyGalleonCBLocations.py
randomizer/Settings.py
static/presets/default.json
wiki-lists/COLORED_BANANAS.MD

- Fixed an issue that prevented starting without a slam
- Some CBs in Galleon above the floating planks now logically require the water to be raised. This isn't all of them, just the ones on the thin planks (not the shop platforms).

Fixed issue forcing starting with slam

---

randomizer/Logic.py

Mitigate the homing ammo accessibility problem by also requiring Forest/Castle entry. This isn't foolproof (lookin at you LZR), but it does cover every S2 scenario.

mitigate homing ammo accessibility problem

---

randomizer/Logic.py
randomizer/Patching/ApplyLocal.py
randomizer/SettingStrings.py
randomizer/Settings.py
randomizer/ShuffleCrates.py
templates/base.html.jinja2
templates/cosmetics.html.jinja2
ui/generate_buttons.py

You can now take your past seeds and essentially export them as .lanky files for easier sharing post-generation. Also updates phrasing in a few small spots on the UI as well as a wonky input on the cosmetics tab.
Also includes the homing ammo accessibility logic fix that was applied to master.

Generate patch from history

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/WrinklyHints.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/LogicFiles/JungleJapes.py
randomizer/Settings.py
templates/progression.html.jinja2
tests/test_spoiler.py

Hints:
- Altered phrasing on path hints from "One item" to "Something" for (hopefully) clarity
- Altered phrasing on path hints to shorten the text slightly
- Kong hints now always show up in your first 20 hints when using Progressive Hints
- Reworded Kong hints so the Kong you are unlocking is always referenced first for consistency. This may trip you up, so make sure you read your hints fully and properly!
Bug Fixes:
- Fixed an issue where too many WotH items would break item hinting hints. For those of you with sicko settings this may literally make your seeds 10% worse.
- Visually adjusted the starting key slider to hopefully be more intuitive at a glance.
- Hard mode lava water now treats Instrument Upgrades as important items. This means they'll be on paths, show in the playthrough, …

Loads of fixes and improvements

---

ui/plando_validation.py

This causes fill issues and it's better to weed it out in the UI.

Prevent users from plandoing shops if Smaller Shops is enabled

---

randomizer/Patching/EnemyRando.py

- Fixed a bug where seeds with Enemy Rando disabled, Crown Enemy Rando enabled and the Win Condition set to Kremling Kapture would crash during boot
I guess you could say it tried to boot K.Rool while booting :P

prevent instant kremling kapture win

---

static/presets/weights/difficult.json
static/presets/weights/standard.json

Due to a mistyped value by me, it's impossible to randomize "difficult" settings. This should fix that.
This also incorporates a suggested change to Open Lobbies.

Fixing difficult random settings

---

randomizer/LogicFiles/CreepyCastle.py
randomizer/Settings.py

- Fixes an Advanced Platforming bug where Krusha can be expected to jump over the gap in Tiny's Mausoleum, and where the Hands part of the GB was not considered anymore.
- Banned ice traps from Aztec Lanky Vulture GB, because it locks a different check.

quick logic fix

---

randomizer/PlandoUtils.py
static/presets/weights/difficult.json
static/presets/weights/easy.json
static/presets/weights/standard.json

Adding updates for recent changes:
- Plando users cannot place ice traps on the locations "AztecLankyVulture" and "AztecDiddyRamGongs".
- The Galleon water level setting is now added to the random settings button.

Updates for plandomizer and random settings

---

randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Spoiler.py

- Added more settings to spoiler logs and also added a section for enabled hard mode options right under Item Pool Section
- Fixed locations of CBs on Mushroom Interior Ladders

Spoiler additions + Mushroom CBs

---

randomizer/Patching/MusicRando.py

If the user tried to assign a vanilla song to a certain location, but also wanted custom songs shuffled in, there was a chance that the vanilla song would be overwritten by the custom song placed in its slot. This PR fixes that bug.

Fix for overwritten assigned songs

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py
randomizer/Settings.py
randomizer/Spoiler.py
tests/test_spoiler.py

- 2 new hint types: Region Potion Counts and Foreseen Pathless. All About Hints will be updated with details.
- Removed garbage hints from being used as filler in item rando. The new hint types are intended to be "better filler."
- Rebalanced hint distributions to favor key path lengths over win condition path lengths.
- Banned items required for helm doors from being on the vanilla helm fairy locations. This mainly affects NSAK and crowns.
- Reorganized the spoiler log to my liking. More important stuff is now grouped at the bottom. Hopefully this didn't break the site cause I didn't check it.

New hints, better filler

---

randomizer/CompileHints.py
templates/plandomizer/plandomizer_hints.html.jinja2
ui/plando_validation.py
ui/rando_options.py

Users can use HTML-like tags to apply colors to their hints, [blue]like this[/blue].
Color tags do not count against the user's character count for their hints. The frontend enforces correct usage of tags.

Add colors to plandomized hints

---

static/js/initalize.js
templates/getting_started.html.jinja2
templates/music.html.jinja2
ui/music_select.py
ui/rando_options.py

Looks like it's best to handle the actual file input in JavaScript, which allows for async lambda functions.
This also fixes a bug where selecting a preset wiped out music selections.

Fix for broken music select imports

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Spoiler.py
tests/test_spoiler.py

- Playthrough paring has been adjusted to be faster for item rando seeds. This shouldn't have any impact on how the WotH is pared because path generation does a more efficient culling of unnecessary locations.
- With the time save, more paths are now being calculated. Paths to major items are now calculated. This includes all non-junk moves, and can sometimes include pearls, the bean, and company coins if they are relevant.
- With the new paths being generated, pathless hints will no longer hint anything on the path to some of the more interesting items. For example if pearls count as a major item (by the same criteria as pearls not being foolish), then nothing on the path to *any* pearl cannot be hinted pathless. This is most helpful for removing things on the path to slams. This should …

Better Pathless

---

randomizer.html
randomizer/Patching/ApplyLocal.py
randomizer/SettingStrings.py
runner.py
static/js/initalize.js

Adds the ability for users to set their unlock times
Removes some data from the spoiler log.
Dealing with trying to parse out the Generation Time and Unlock Time from the spoiler on the site seems to be a bit of a pain so I've opted to leave the EPOCH timestamps in the spoiler log, it might confuse people but could be worse. We can always do something later if we care.
Solves https://github.com/2dos/DK64-Randomizer/issues/1774 and https://github.com/2dos/DK64-Randomizer/issues/1797

Allows users to set the time for unlocks

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/Settings.py
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2
tests/test_spoiler.py
ui/generate_buttons.py
ui/rando_options.py

- Fixed an issue (again) where applying a preset didn't immediately cache the settings
- Fixed an issue where spoiler-hint-adjacent settings weren't being cached
- Fixed an issue where a few UI elements weren't correctly updating in some scenarios
- With the addition of the third slam you can now start with 41 moves, and the starting move selector has been adjusted to account for this
- Fixed issues with starting with a ton of moves and item hinting hints. You will now actually get filler hints (it won't be good filler, but you'll get filler alright) and not a bunch of errors.
- There is now a limit on funny joke hints in a seed. Wrinkly will get fed up with your nonsense after a few.
- Fixed an issue in LZR where you might have been expected to clear the Mechfish without diving
- Fixed …

Starting move count, caching, logic fixes

---

randomizer/Spoiler.py
templates/macros.html.jinja2
templates/music.html.jinja2
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2

- Fixed an issue where progressive hints + not removing wrinkly puzzles would error during patching
- The multiselectors on the site were observed to have inconsistent behavior. Numerous tooltips have been adjusted and text has been added to clarify the behavior of the multiselector modals. No functionality has changed, this is purely a visual update.

improved multiselector tooltips, fixed a door issue

---

runner.py

Solves an edge case where an incorrect value is passed to the delayed spoiler log release
If it catches an error, it'll just set to never release unless the spoiler log is still wanted

Except ValueError

---

static/presets/weights/weights_files.json

- "Dim Solved Hints" is now 50% on Standard, and always off on Difficult, after user feedback.
- Irondonk is too severely difficult for random settings, and is now always off.
- FPS Display and Cutscene Skips are no longer randomized, and will retain the player's preferred settings.

Adjusting random settings

---

.gitignore
generate_rando_ui.py
randomizer/Patching/ApplyLocal.py
randomizer/Patching/ApplyRandomizer.py
runner.py

- Changes utcnow to be now(UTC) per python sunsetting
- Supports local_preset files so we can manually update presets on the live site based on changes with a redeploy
- Adjusts the current_total so we can symlink the cfg file to track both live and dev

Various Adjustments

---

.bumpversion.cfg
index.html
randomizer.html
randomizer/Lists/KasplatLocations.py
randomizer/Patching/KasplatLocationRando.py
version.py
wiki-lists/CUSTOM_LOCATIONS.MD
wiki-lists/KASPLATS.MD

- Enlarged the underwater kasplat in caves
- Added an additional underwater kasplat in caves
PR note: melon crates are still banned in the Galleon alcove. the linter just thought it shouldn't be mentioned in the .MD file

Kasplat updates

---

randomizer/CollectibleLogicFiles/CreepyCastle.py
randomizer/CollectibleLogicFiles/CrystalCaves.py
randomizer/CollectibleLogicFiles/FungiForest.py
randomizer/CompileHints.py
randomizer/Lists/CBLocations/AngryAztecCBLocations.py
randomizer/Lists/CBLocations/CreepyCastleCBLocations.py
randomizer/Lists/CBLocations/CrystalCavesCBLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CBLocations/GloomyGalleonCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py
randomizer/Lists/WrinklyHints.py
randomizer/LogicFiles/DKIsles.py
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

- Fixed one more cb custom location that had issues with Krusha
- Cleaned up some cb logic that would make you do degenerate things with phasewalking
- Added camera/shockwave to points hints. They are tied to the training move point value. In a future major version they will get their own point box.
- Fixed an issue where a few (rare) specific combinations of Switchsanity and Bonus Barrel rando could cause the Helm lobby barrel to be logically impossible.

cb logic cleanup, switchsanity fail fix, shockwave spoiler value

---

randomizer/Patching/ItemRando.py

- The mermaid will now also tell you the reward if you already more than 0, and less than 5 pearls with the Galleon Mermaid GB Faster Checks setting disabled.

that's what she said

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Settings.py
tests/test_spoiler.py

- Fixed a comically complicated error that could occur when random starting locations were enabled that might cause your seed to be logically unbeatable.
- Fixed an issue where you couldn't start with moves when the item randomizer is disabled or shops are not in the item rando pool

fix reshuffling random starting location, non item rando starting moves

---

randomizer/CompileHints.py
randomizer/LogicFiles/FungiForest.py

- Fixed an enemy incorrectly being in the Forest blast course
- Fixed an enemy with incorrect logic in the tunnel to Forest Funky
- Fixed a rare care where a shortened hint might be worse than the original

fix forest enemies, short training hints

---

randomizer/Lists/Minigame.py
randomizer/Settings.py

Rebalanced Helm doors with the following generic criteria:
- Easy doors: 10-25% of an item
- Medium doors: 25-50% of an item
- Hard doors: 50-75% of an item
Also removed diving requirement for Enguarde arena because you don't need it

rebalance helm doors, enguarde no dive

---

randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

- Temporarily removed a potential colored banana location in Fungi Baboon Blast (there's sitll the vanilla location there) due to Krusha's unfortunate bone structure.
- Moved the Japes CB's next to Snide a bit more away from Snide's HQ, so that they don't clip into Funky's Armory as much.

disable fungi cb group 79

---

randomizer/CompileHints.py
randomizer/Enums/Types.py
randomizer/Lists/EnemyTypes.py
randomizer/Lists/Location.py
randomizer/Spoiler.py
static/presets/preset_files.json
tests/test_spoiler.py

Hint Changes:
- The number of path hints you get is no longer based on the length of paths. That number is now 65% (randomly rounded) of the total number of multipath-eligible locations. This is intended to be a slight buff to the average seed and a more noticeable buff to the worst seeds.
- Buffed the duplication prevention mechanism
- Removed Wrinkly Helm Order hints, as it is now always available at Snide's
- Removed Wrinkly K. Rool Order hints if you have spoiler hints enabled because it's redundant
- Fixed an issue where overhinted seeds might error out
- Fixed an issue where you might try to receive more multipath hints than there are multipath-eligible locations
- Altered the phrasing on a certain special joke hint to not be misleading with the context of the cumulative hint …

Hint Rebalance and other fixes

---

randomizer/LogicFiles/DKIsles.py

- Krusha can no longer be logically expected to jump to Caves Lobby. Not even with advanced platforming turned off

Caves Lobby jump

---

randomizer/CompileHints.py
randomizer/Settings.py
tests/test_spoiler.py
ui/generate_buttons.py
ui/rando_options.py

Last few fixes in this PR, I expect this to go to master and then we move to 4.0
- Prevent foolish hints for medal regions when medals aren't in the pool
- Remove K. Rool Order hints when multipath hints will appear, as these hints will indirectly hint K. Rool phases already
- Fix a corner case where it would try to hint more multipath hints than the distribution would expect
- Settings strings are now trimmed on import in case you copy a leading or trailing space
- Fix max random B. Lockers being floored at 8

Last Call for S3 Fixes

---

randomizer/Patching/MusicRando.py
randomizer/SettingStrings.py
randomizer/Settings.py
templates/music.html.jinja2

This option will ensure that vanilla songs are not shuffled into any locations other than their original locations. This will not affect user-assigned songs, or the proportions or locations of custom songs.

Add "Keep vanilla song placements" option

---

randomizer/Fill.py
randomizer/Settings.py

- Guarantee a buffer of at least 1 no matter the number of medals or fairies required for Jetpac and BFI
- Jetpac can no longer be hinted foolish because Cranky always tells you this info anyway

better buffers, no jetpac foolish

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Patching/MusicRando.py
randomizer/Settings.py
randomizer/ShuffleItems.py
randomizer/Spoiler.py

Hints:
- Freeing Kongs is now a path endpoint. Anything that will help you free kongs is eligible to be hinted this way. Items can be hinted to exclusively freeing kongs just like any other path endpoint. This has the effect of slightly increasing the amount of path hints seen, but probably not to a significant extent. This is intended to assist with kong casinos, particularly in settings without SLO's guide rails.
- A random wrinkly door and the last progressive hint are now guaranteed to be the equivalent to the slam microhint. This guarantee is contingent on it actually being relevant: if you start with less than Super Simian Slam, you will receive this hint.
Fill & Friends:
- Reworked the fill to reduce the inherent biases observed over the lifespan of 2.0 and beyond. By lumping …

Fill rework and kong paths

---

randomizer/CompileHints.py
randomizer/Fill.py

- If you start with two slams, you are now limited to one "your training with progressive slam..." hint
- Prevented Jetpac scouring hints

double slam start, no jetpac scouring

---

randomizer/CollectibleLogicFiles/FranticFactory.py
randomizer/CompileHints.py

- Blast should not be hintable if you start with it and it's only on the path to Donkey Phase
- Fixed a position of the dark room Chunky CBs. This would only be noticeable in some rare worlds where you didn't start with a slam.

training blast hint fix, correct cb positioning

---

randomizer/CompileHints.py
randomizer/Lists/PathHintTree.py
randomizer/Spoiler.py

- Path hints that point to T&S no longer exist, those hints are folded into "collecting CBs in {level}" hints
- Removed a joke hint that might be lying when shopkeepers are in the pool
- Shopkeepers count as Kongs for the purposes of vial hints
- Initial implementation for distilling the "unhintedness" of locations and whole seeds into a single score. This implementation is limited in scope, does not reflect all hint types, and generally is liable to come up wtih some false positives. It most needs manual feedback to improve however, so out into the wild it goes

no more path to tns, unhinted score attempt

---

randomizer/Fill.py
randomizer/Lists/CBLocations/AngryAztecCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py
randomizer/Lists/PathHintTree.py
randomizer/LogicFiles/DKIsles.py
ui/rando_options.py
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

- Fixed some bad logic on a few CB groups
- Fixed an issue where a vanilla camera/shockwave would never succeed in the fill
- Fixed an issue where vanilla company coins might break the fill when calculating unhinted score
- Tweaked the UI to prevent Shuffle Kongs from being unselected while Kongs are in the item pool

CB fixes, Vanilla Camera fix, comp coin hint tree fix, UI tweak

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/MapsAndExits.py
randomizer/Lists/PathHintTree.py
randomizer/Patching/ItemRando.py
randomizer/Spoiler.py
tests/test_spoiler.py

- CB path hints have been rephrased to be slightly less wordy. Foolish CB hints are now consistent with this phrasing.
- Endgame goals have been rephrased to be slightly less wordy
- Endgame goals have been directly colored instead of the bit before them
- Fixed an issue with entrance hints and Isles medals
- Fixed a rare issue with a DK portal location in Helm and LZR
- Fixed an issue where the combination of Chaos B. Lockers, CLO, and not having Keys in the item pool would fail to gen.
- Fixed an issue that might arise if a training move got placed in a training barrel with fast start off

Recolor and Rephrase Hints

---

static/presets/weights/weights_files.json

DK Phase Requires Blast:
- Easy: 0%
- Standard: 50%
- Difficult: 100%
- Difficult w/ QoL: 100%
Colored Banana Shuffle:
- Easy: Off (70%), On (30%) (Unchanged)
- Standard: Off (50%), On (40%), On With Isles (10%)
- Difficult: Off (40%), On (30%), On With Isles (30%)
- Difficult w/ QoL: Off (40%), On (30%), On With Isles (30%)
Chaos B. Lockers:
- Easy: 0%
- Standard: 25%
- Difficult: 60%
- Difficult w/ QoL: 60%
Chaos Ratio:
- Standard: Min 0.1, Max 0.35, Mean 0.25
- Difficult: Min 0.25, Max 0.7, Mean 0.4
- Difficult w/ QoL: Min 0.25, Max 0.7, Mean 0.4
Chunky Phase Slam Requirement:
- Easy: Slam (30%), Super Slam (70%)
- Standard: Random (100%)
- Difficult: Super Slam (70%), Super Duper Slam (30%)
- Difficult w/ QoL: Super Slam (70%), Super Duper Slam (30%)
Shuffle DK Portals:
- Easy: 0%
- …

Adding new 4.0 settings to random settings

---

randomizer/ShuffleCoins.py

If trying to place a coin into a region which doesn't have any associated coins/cbs in that region, it'll properly create the dict item

Proper fix for the coins thing

---

randomizer/Fill.py
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2
ui/__init__.py
ui/rando_options.py

Gotta ban fast start off + (LZR or random starting location)
This setup leaves room to ban settings in both the front end and the back end if we know they'll cause problems

Prevent fast start off with some settings

---

ui/rando_options.py

- Fixed a bug where enabling LZR, DLZR or Random Starting Location would force *disable* Fast Start, instead of force *enabling* it.

A small fix for dev, a giant fix for playerkind

---

ui/plando_validation.py

Previously, if the user turned Switchsanity on when using the plandomizer, all of the switches would default to their vanilla settings. Now, turning on Switchsanity will set the corresponding switches to "Randomize" to match expected behavior. (This works correctly for all three Switchsanity settings.)

Fix switchsanity behavior when using plandomizer

---

randomizer/Enums/Plandomizer.py

I suspect this might have something to do with a plando bug regarding climbing.

Add climbing to the reverse PlandoItems map

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py

- Plando can now properly plando all 35 hints without fear of hint failures
- Item hinting hints are now placed by the number of hint doors they have available. This will generally put hints to accessible items on accessible hints more often.
- Item hinting hints now include shopkeepers
- Progressive hints now have restrictions on hints to keys that unlock levels to provide a more consistent flow of hint knowledge. The restrictions are as follows:
- In SLO, Hints to Keys 1/2 will be found by pack 5
- In SLO, Hints to Keys 3/4 will be found by pack 7
- In SLO, Hints to Key 5 will be found by pack 8
- In CLO, Hints to Keys 1, 2, 4, and 5 will be found by pack 8
- Hints to Kongs are unchanged (by pack 5)
- This will (attempt to) affect WotH hint placement too!

Improve hint flexibility

---

randomizer/Lists/CBLocations/DKIslesCBLocations.py
randomizer/Lists/CustomLocations.py
randomizer/Lists/DoorLocations.py
randomizer/Settings.py
randomizer/ShufflePorts.py
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD
wiki/article_markdown/custom_locations/CustomLocationsDoors.MD
wiki/article_markdown/custom_locations/CustomLocationsMiscellaneous.MD

- Fixed a bug preventing seeds with vanilla bananaport location shuffle from generating
- Fixed plando k.rool phases resolving to exclusively k.rool phases when set to Random (regardless of k.rool phases in boss pool setting)
- Fixed a CB group in Training Grounds not requiring climbing when it should
- Fixed the Aztec Level entrance spawning on quicksand
- Fixed another location where a meloncrate could block autowalking out of a tns portal

minor fixes

---

ui/plando_validation.py

This was a case of unintended side effects.

Plandomizer: vanilla switches no longer revert to Randomize when changing tabs

---

static/js/rando_options.js

Since Wrinkly door shuffle now works with progressive hints, plandomizer should allow it as well.

Allow for Wrinkly doors to be plando'd with progressive hints

---

randomizer/Fill.py
static/presets/preset_files.json
tests/test_spoiler.py

Fixed an issue where scouring hints would only hint shop regions instead of only NOT-shop regions
Updated BLZR - Climbing returns as a starting move and the Extra microhints are removed

Unbork scouring hints

---

randomizer/Fill.py
randomizer/ShuffleBosses.py
randomizer/ShuffleDoors.py
randomizer/ShuffleExits.py

- Fixed K. Rool logic using the wrong phases.
- Removed the "Unable to fill Helm" error. We're no longer filling Helm first.
- Fixed Helm being level 1 or 2 in SLO
- Fixed Japes alcove tns generating

Seed gen fixes

---

randomizer/CompileHints.py
randomizer/Enums/Settings.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Item.py
randomizer/Lists/Plandomizer.py
randomizer/Patching/ASMPatcher.py
randomizer/Patching/ItemRando.py
randomizer/Patching/Lib.py
randomizer/Settings.py
randomizer/ShuffleItems.py
randomizer/Spoiler.py
tests/test_spoiler.py

- Fixed entrance hints not properly traversing through connectors indefinitely
- Reworked the climbing Types to isolate climbing as a setting. This fixes the issue where intentionally starting with climbing could still cause climbing to be hinted as a training move.

connector hint fixes, climbing type rework

---

randomizer/ItemPool.py

- Fixed plando seeds not generating when placing more than 1 blueprint per kong (odds increased drastically with more plandomized blueprints)

Failed to place 0 blueprints

---

randomizer/Enums/Events.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Logic.py
randomizer/LogicFiles/DKIsles.py
randomizer/Settings.py
randomizer/ShuffleBosses.py
randomizer/Spoiler.py

CLO Progression Fixes:
- The algorithm now properly accounts for Helm in the main level order. The algorithm will consider Helm to be a possible next level if and only if you have the ability to traverse the lobby. Helm doesn't have to be the most expensive B. Locker, but it often will be because of that (see also: level 4, Aztec and Vines)
- Fixed an issue where progression could fail if you had DK Portal rando on. The algorithm will no longer expect you to have Vines before it considers Aztec as a possible next level. This means your Aztecs will likely be somewhat cheaper on average relative to when DK Portal rando is off.
- Fixed an issue where CLO and Keys not being in the item pool would fail for several reasons.
- Fixed an issue with boss placement where certain combinations of …

Several CLO progression fixes

---

randomizer/Lists/EnemyTypes.py
randomizer/Patching/EnemyRando.py
randomizer/Settings.py

- Reduce the default size of Klobbers/Kabooms
- Disable size rando in beaver bother/busy barrel barrage
- If size rando is off, enemy sizes will no longer be normalized

Enemy fixes

---

randomizer/Enums/Plandomizer.py
randomizer/PlandoUtils.py

- Users can now place Kongs as a reward on the Japes rock. Why would anyone want to do this? Ask SniperWave.
- Users can now place shopkeepers as rewards. They cannot be placed in shops.

Plandomizer: Japes rock and shopkeepers

---

randomizer/Enums/Plandomizer.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Logic.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/HideoutHelm.py
ui/plando_validation.py

- Improved the error codes to be both more and less human understandable. A gibberish error code was added if we needed to identify a specific location pointed out by the error, but this isn't common.
- Added the ability to plando hint items
- Paths now assume level 8 entry. This means MP (or whatever replaces it in switchsanity) will not be on the path to everything in level 8. This does **NOT** apply to the top level checks like the sax pad or Pound the X - these should still have MP on the path to them. Let me know if some path or WotH looks suspicious.
- Fixed an issue where the logic might expect you to exit Helm before it's shut off in LZR
- Fixed an issue with plando where it might force Key 8 to be at the End of Helm when it didn't need to be there

Better error codes, bug fixes

---

runner.py

Fixes [https://github.com/2dos/DK64-Randomizer/security/code-scanning/41](https://github.com/2dos/DK64-Randomizer/security/code-scanning/41)
To fix the problem, we need to ensure that the constructed file path is securely validated before being used. This involves normalizing the path and ensuring it is contained within a safe root directory. We will use `os.path.realpath` to resolve the absolute path and then check that it starts with the intended directory.
1. Normalize the path using `os.path.realpath` to remove any ".." segments.
2. Check that the normalized path starts with the `generated_seeds/` directory.
3. Update the code to use the validated path for file operations.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 41: Uncontrolled data used in path expression

---

runner.py

Fixes [https://github.com/2dos/DK64-Randomizer/security/code-scanning/39](https://github.com/2dos/DK64-Randomizer/security/code-scanning/39)
To fix the problem, we need to ensure that the constructed file path is securely validated. This involves:
1. Normalizing the path using `os.path.normpath` to remove any ".." segments.
2. Ensuring that the normalized path starts with the intended base directory.
3. Using `werkzeug.utils.secure_filename` to sanitize the file name.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 39: Uncontrolled data used in path expression

---

runner.py

Fixes [https://github.com/2dos/DK64-Randomizer/security/code-scanning/40](https://github.com/2dos/DK64-Randomizer/security/code-scanning/40)
To fix the problem, we need to ensure that the constructed file path is contained within a safe root folder. We can achieve this by normalizing the path using `os.path.normpath` and then checking that the normalized path starts with the root folder. Additionally, we should use `werkzeug.utils.secure_filename` to sanitize the `hash` parameter to eliminate any special characters.
1. Import `secure_filename` from `werkzeug.utils`.
2. Use `secure_filename` to sanitize the `hash` parameter.
3. Normalize the constructed file path using `os.path.normpath`.
4. Check that the normalized path starts with the root folder.
_Suggested fixes powered by Copilot …

Fix code scanning alert no. 40: Uncontrolled data used in path expression

---

static/js/initalize.js

This pull request includes changes to the `static/js/initalize.js` file to improve the handling of preset selections and ensure the default preset is loaded correctly.
Enhancements to preset handling:
* [`static/js/initalize.js`](diffhunk://#diff-2a83f41f58bc5257f5563b4d7893fbb64c2e7227169b21f0d56c5521be7999f1R610): Added a call to `preset_select_changed("default")` in the `load_databases` function to ensure the default preset is selected when the database is initialized.
* [`static/js/initalize.js`](diffhunk://#diff-2a83f41f58bc5257f5563b4d7893fbb64c2e7227169b21f0d56c5521be7999f1R1119-R1133): Modified the `preset_select_changed` function to handle string events, allowing the selection of the "Beginner Settings" preset when the event is a string.

Set default preset

---

randomizer/Fill.py

Missed an inversion - this meant that minigame logic was not being applied when it should and applied when it shouldn't.

minigame logic fix

---

static/presets/weights/weights_files.json
wiki/article_markdown/custom_locations/RandomSettingsDifficult.MD
wiki/article_markdown/custom_locations/RandomSettingsDifficultWithQolShuffle.MD
wiki/article_markdown/custom_locations/RandomSettingsStandard.MD

These needed to be percentage values instead of decimals.

Random settings: fix for chaos ratio

---

randomizer/Fill.py
randomizer/Spoiler.py
templates/macros.html.jinja2
templates/music.html.jinja2
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2

- Reworked how the WotH paring would handle things not on the path to anything else. Now it checks if the items are necessary to beat the game with fewer assumptions. If it is still required to beat the game, it remains WotH.
- Added fill exceptions for when the extremely rare pathless phase would leak through the path generation. It now crashes out and prompts the user to report it. This is far, far, FAR, **_FAR_** better than letting the seed leak out into the world.
- Fixed an issue where the multiselector disclaimer about "when none are selected all are selected" wasn't appearing for some reason. This was fixed by making it a 0/1 int switch instead of a boolean, which worked for ??? reasons.

woth level access fix (and friends

---

randomizer/Fill.py

Fixed an issue where starting with all training moves wasn't properly accounted for in an error safeguard, making it trigger more than it should.

accounting for barrels in rare error safeguard

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Logic.py

Spoiler Hints Update
Starting moves are no longer a part of Isles and have been given their own section in the spoiler hints. This will include everything that you see when you see the file select screen for the first time.
This has a couple of implications:
- For points and vials, you no longer have to mentally account for the starting moves when calculating how stacked (or not) Isles is.
- For WotH moves, you can see how many of your starting moves are WotH - keep in mind settings that affect what starting moves can be hinted WotH!
Other fix:
- Fast start off has been improved to account for more settings combinations. As a result, you ***must*** be guaranteed to start with a slam when turning off Fast Start. This will force Cranky to give you your Simian Slam to escape the training …

Starting moves separate

---

ui/plando_settings.py
ui/plando_validation.py

The plando dropdowns will no longer automatically disable starting moves, because the starting move selector is getting a bit too complicated for that sort of thing.

Removing plando check re: starting moves

---

randomizer/CompileHints.py
randomizer/Settings.py
static/js/rando_options.js

- Fixed an issue where CLO T&S could roll noticeably lower than intended
- Item Hinting hints now also combine a level's medal rewards and boss when pointing at something you could obtain by collecting colored bananas. This is to match the behavior of path hints hinting things in the same way.
- Fixed an issue where the "Move Randomizer" dropdown that nobody uses wasn't working quite right, preventing some settings from being created.

Fix CLO T&S

---

randomizer/Fill.py
randomizer/LogicFiles/DKIsles.py
randomizer/Settings.py
randomizer/Spoiler.py

- Banned the Krem Isle Mouth entrance from being your random starting location in Quad Damage and OHKO
- Cleaned up the logic around the Krem Isle Mouth region to better handle some weirdly specific circumstances
- Shuffled some incompatible settings checks around to not crash out when patching from a lanky file. This isn't complete, as we need to handle a couple plando checks somewhere else as well. This PR just covers the most likely issues.

Krem Isle Dentistry

---

static/js/rando_options.js
static/styles/gui.css
templates/rando_options.html

Improved the user experience of the starting move selectors:
- A color outline will help visually indicate if you are going to start with all/some/none of the items in that pool
- Pools beyond the first empty item pool will no longer be shown to simplify the modal some. There is still a cap of 5 pools.

Color/Status for Starting Move Pools

---

dumper.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/Patching/Cosmetics/EnemyColors.py

- Fixed a logic bug where death warps with conditional logic were expected to lead to the vanilla start of the level.
- Fixed a bug where seeds would fail on the patching phase, when Random Enemy Colors was enabled.

Fix deathwarps

---

randomizer/Enums/Settings.jsonc
randomizer/Fill.py
randomizer/Lists/DoorLocations.py
randomizer/Settings.py
randomizer/ShuffleDoors.py
randomizer/Spoiler.py
static/js/rando_options.js
templates/rando_options.html
typings/randomizer/Enums/Settings.d.ts
typings/randomizer/Enums/Settings.pyi

Introduced a new door placement variant: Dos' Doors:
- This is a variant on Vanilla Door Shuffle that leverages vanilla locations to rebalance hint door locations
- Exactly one hint door will be placed in each lobby. The location of this door will not change, and it will always be accessible.
- Exactly one T&S will be placed in the game on an eligible location in each level.
- Eligible locations for that T&S and the remaining hints doors are the vanilla T&S locations.
- Exception: Japes only has 3 T&S portals, so we include the level entry portal and a custom location in the Hive area.
- Dos' Doors enforces DK Portal rando to not be off

dos' doors implementation

---

static/js/generate_buttons.js
static/js/initalize.js
static/js/music_select.js
static/js/rando_options.js
ui/plando_settings.py
ui/plando_validation.py

This pull request includes multiple changes across several JavaScript files to clean up and simplify the codebase by removing unnecessary calls to the `savesettings` and `savemusicsettings` functions. The most important changes are grouped and summarized below.
* [`static/js/generate_buttons.js`](diffhunk://#diff-e9ee7c494bdb576dca9cf391c3cbe7389bf3feafdff5e28275fca2b644e77ac3L555): Removed the `savesettings` call from `import_settings_string` function.
* [`static/js/initalize.js`](diffhunk://#diff-2a83f41f58bc5257f5563b4d7893fbb64c2e7227169b21f0d56c5521be7999f1L1337): Removed the `savesettings` call from `trigger_preset_event` and `load_data` functions. [[1]](diffhunk://#diff-2a83f41f58bc5257f5563b4d7893fbb64c2e7227169b21f0d56c5521be7999f1L1337) …

cleanup settings logic

---

randomizer/CollectibleLogicFiles/FungiForest.py
randomizer/Enums/Regions.jsonc
randomizer/Fill.py
randomizer/Lists/BananaCoinLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CustomLocations.py
randomizer/Lists/FairyLocations.py
randomizer/Lists/MapsAndExits.py
randomizer/LogicFiles/FungiForest.py
randomizer/ShufflePorts.py
typings/randomizer/Enums/Regions.d.ts
typings/randomizer/Enums/Regions.pyi
wiki/article_markdown/custom_locations/CustomLocationsCoins.MD
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD
wiki/article_markdown/custom_locations/CustomLocationsFairies.MD
wiki/article_markdown/custom_locations/CustomLocationsMiscellaneous.MD

- Added a new region to the mushroom exterior for the level the blast platform is on. This is remove the climbing requirement from a number of checks and collectibles on that level.
- Fixed an issue where SLO + Helm Key Lock could put a Key in a location it could not otherwise normally be placed.
- Altered the WotH paring algorithm so it doesn't double check sans-assumptions in LZR. LZR doesn't leverage these assumptions in a way that should confuse paths, so it *should* already be properly culling things without double checking.

Add new level to mushroom exterior

---

randomizer/Fill.py
randomizer/Logic.py
wiki/article_markdown/custom_locations/CustomLocationsDoors.MD
wiki/article_markdown/custom_locations/CustomLocationsMiscellaneous.MD

- Removed BanItems, it's just not effective when handling progressive items.
- Fixed the pathless double checking flow by properly culling when it should and ensuring Kongs stay assumed during the double check. This was causing items to not be WotH when they should and sometimes causing items to be WotH when they shouldn't.

fixed the double checking tomfoolery

---

randomizer/CompileHints.py
randomizer/Lists/DoorLocations.py

- Fixed some logic that'd dictate when DK portals are allowed to exist in certain locations (because it'd otherwise brick seed gen)
- Fixed a bug where Snide could still be hinted, when you start with him unlocked.
- Fixed a bug where Wrinkly would pick the wrong crayon to colour part of her hints, sometimes.

dk portal logic and crayon

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/DoorLocations.py
randomizer/Lists/Exceptions.py
randomizer/Settings.py
randomizer/ShuffleBosses.py
templates/plandomizer/plandomizer_general.html
wiki/article_markdown/custom_locations/CustomLocationsDoors.MD

- Fixed an issue where boss plando would fail if Helm wasn't level 8
- Reworded the exception thrown when not all locations are reached on the first attempt to be less confusing (again)
- Climbing is now a "training move" in advanced item hinting
- Prevented a few more underwater doors from being DK Portals

fixed boss plando w/ helm shuffled, better generic failure exception

---

randomizer/Fill.py

- Fixed an issue where WotH paring could extremely rarely pare out WotH items needed to get into levels that only have required Kongs within
- Fixed an issue where WotH paring even more extremely rarely pare out WotH Kongs needed only to perform certain events

Robust woth paring for insanely rare scenarios

---

randomizer/Patching/Cosmetics/KongColor.py

- Reverted "Chunky's vest will always have a checkered pattern on its back using opposite colors. The sides now use the secondary color."

revert chunky cosmetics change

---

randomizer/Lists/EnemyTypes.py
randomizer/Patching/EnemyRando.py

- Fixed a bug where the game would freeze if too many enemies of certain types are gathered in a small space. (Robo-kremlings, and if we want to revert the spider fix Spiders will probably also end up there)
- Enemies that don't respawn will no longer count towards the list of enemies needed for the kremling kapture win condition.

DK64 Tropical Freeze

---

randomizer/Lists/DoorLocations.py
randomizer/ShuffleDoors.py
static/js/rando_options.js

A custom location near the vanilla Japes level portal is now used instead of the vanilla level portal location for Dos' Doors. This has the benefit of no longer needing to force DK Portal Rando on with Dos' Doors enabled.

Moved Japes Dos Door

---

randomizer/Lists/DoorLocations.py
randomizer/Settings.py
static/js/rando_options.js
templates/qualityoflife.html

- Fixed an issue where DK Portal Rando would still occasionally try to assign invalid doors (because the dk_portal_logic wasn't correctly filtering out doors)
- Fixed an issue where Dos' Doors silently forced DK Portal Rando to be on (woops!)
- Fixed some cogs on the UI to properly disable when the corresponding setting is disabled

Door Fixes, UI Fix

---

controller/app.py
randomizer/CompileHints.py
templates/admin.html

- WotH Keys found in shops with nothing else on the path to them will no longer be eligible for WotH hints
- Added some buttons to the admin panel to let us reorder the settings string list

No WotH Shop Keys, Admin Strings Reordering

---

randomizer/Patching/ASMPatcher.py

- Locks the bigger textboxes behind useful wrinkly door hints or item reward previews
- Removes the GB HUD with bigger textboxes

Why do you have to be so persuasive, Mumbo

---

controller/app.py

- Spoiler logs, created to display info about the seed in a human-readable format, will now be correctly human-readable. (Spoiler logs were sorted alphabethically for some reason)

sorting spoils the log

---

randomizer/Lists/CustomLocations.py

Fixed logic to a location in helm lobby, to account for switchsanity

Custom location logic fix

---

randomizer/CollectibleLogicFiles/DKIsles.py
randomizer/CompileHints.py
randomizer/Enums/Events.jsonc
randomizer/Enums/Regions.jsonc
randomizer/Fill.py
randomizer/Lists/CBLocations/DKIslesCBLocations.py
randomizer/Lists/MapsAndExits.py
randomizer/Lists/ShufflableExit.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/HideoutHelm.py
typings/randomizer/Enums/Events.d.ts
typings/randomizer/Enums/Events.pyi
typings/randomizer/Enums/Regions.d.ts
typings/randomizer/Enums/Regions.pyi
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

- Split Helm Lobby into 2 regions to account for being able to warp between sides once you have found each side
- Fixed an issue where Exit Level transitions weren't properly being utilized in some circumstances (by deleting the cache)

Rare instance of LZR having clean fixes

---

ap_version.py
controller/Dockerfile
controller/app.py

This pull request introduces a new versioning system for the Archipelago project by adding a version file and updating the relevant Dockerfile and application code to incorporate this change.
* [`ap_version.py`](diffhunk://#diff-eedb3380dcf36b1ddad17bb7adb36762f81b4a723b72988cbce995d65dcf1e0eR1-R3): Added a new file to hold the version for Archipelago.
* [`controller/Dockerfile`](diffhunk://#diff-df234eb86d676bd9233f232e9dc9af4895969477a6a9ff9161e32621f6ce76d1L30-R31): Updated the Dockerfile to move the new `ap_version.py` file to the appropriate directory.
* `controller/app.py`: 
* Imported the Archipelago version from `ap_version.py`.
* Added a new endpoint `/ap_version` to return the Archipelago version.
* Minor formatting improvement by removing an unnecessary blank line.

Support version for AP

---

__init__.py
ap_version.py
randomizer/Patching/Patcher.py
worker/tasks.py

This pull request includes several changes to improve file handling and simplify the codebase in the `randomizer` module. The most important changes include modifying file paths, removing unused parameters, and updating global variable usage.
File handling improvements:
* [`__init__.py`](diffhunk://#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cL458-R459): Updated the file path in the `generate_output` method to use the `output_directory` parameter instead of a hardcoded path.
Codebase simplification:
* [`randomizer/Patching/Patcher.py`](diffhunk://#diff-282170d1bb253e272020d4f14dd1af1df2f5ff910b4d2de85d72c42523b1495dL131-L136): Removed the `default_file` parameter from the `load_base_rom` method and updated the method to return `og_patched_rom` directly. …

Adjust Patcher to no longer use Global

---

__init__.py
ap_version.py
archipelago/Items.py
archipelago/Options.py
archipelago/Regions.py

- Added All Keys win condition to the Goal options in AP yamls
- Fixed an issue where pre-activated Isles warps weren't considered in AP logic
- Cranky now considers progressive AP items to be major items when hinting what is on Jetpac
- The starting Kong is now in the AP spoiler log and AP start inventory

AP All Keys Win Con

---

randomizer/Logic.py

Apply the Kongless Hint Door setting to the logic so you don't have to have the Kong to logically access a hint door. This greatly increases hint door availability for early items.

Apply kongless hint door logic

---

__init__.py
ap_version.py
tools/package_apworld.py

This pull request introduces several updates, including changes to dependency management, cleanup of outdated files, and a version increment for the Archipelago project. The most notable changes involve replacing the use of a fixed directory for dependencies with a temporary directory, improving the cleanup logic, and updating the project version.
* Updated `copy_dependencies` in `__init__.py` to use a temporary directory (`tempfile.mkdtemp`) instead of the fixed `./lib` directory for extracting and managing dependencies. The temporary directory is added to `sys.path` dynamically. [[1]](diffhunk://#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cL41-R60) [[2]](diffhunk://#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cL81-R105)
* Enhanced the …

Swap how we stash packages

---

ap_version.py
randomizer/ShuffleBosses.py

```
Traceback (most recent call last):
File "__startup__.py", line 121, in run
File "console.py", line 25, in run
File "Generate.py", line 552, in <module>
File "Main.py", line 359, in main
File "concurrent\futures\_base.py", line 449, in result
File "concurrent\futures\_base.py", line 401, in __get_result
File "concurrent\futures\thread.py", line 59, in run
File "Main.py", line 269, in write_multidata
File "C:\ProgramData\Archipelago\custom_worlds\dk64.apworld\dk64\__init__.py", line 591, in fill_slot_data
File "C:\ProgramData\Archipelago\custom_worlds\dk64.apworld\dk64\__init__.py", line 591, in <genexpr>
AttributeError: 'int' object has no attribute 'name'
```
KRool kongs are stored as ints instead of Kong enums is the reason this happens. Slot data expects the Kong enum.

Fix AP gen bug

---

static/presets/weights/weights_files.json

Without these settings listed, they are always set to off, as we discovered in today's random settings race.

Adding misc changes to random settings

---

randomizer/Lists/CustomLocations.py
randomizer/ShufflePorts.py

Banned all custom locations that have non-trivial access logic from being warps. This saves us a veritable mountain of logic headaches from accessing pre-activated warps in unexpected ways

Prevent bad warp location logic

---

ap_version.py
archipelago/DK64Client.py

This pull request introduces enhancements to the Donkey Kong 64 client, including the addition of new command processing capabilities, a utility function for handling death events, and a version update. The most significant changes focus on improving the Deathlink feature by adding commands to toggle and reset its state.
* Added a `safe_clear_death_events` method to handle clearing pending death events, ensuring the Deathlink state is reset safely. (`archipelago/DK64Client.py`, [archipelago/DK64Client.pyR563-R594](diffhunk://#diff-2e2a10dbf06e376df9f46c4a4b442ccd5d63b70ef1bbaa8eacf0c26e5eb727f0R563-R594))
* Introduced the `DK64CommandProcessor` class, extending `ClientCommandProcessor` to include `_cmd_reset_deathlink` and `_cmd_deathlink` commands for resetting and toggling Deathlink …

Create safety functions for deathlink

---

randomizer/ShufflePorts.py

Fixes an issue with ShufflePorts using the wrong form of an enum

variable name consistency is a myth

---

ap_version.py
archipelago/DK64Client.py

This pull request introduces a version update for Archipelago and adds new functionality to the `DK64Client` for toggling additional features (`Taglink` and `Ringlink`). The changes enhance the client-side control over these features and improve the overall flexibility of the application.
* [`ap_version.py`](diffhunk://#diff-eedb3380dcf36b1ddad17bb7adb36762f81b4a723b72988cbce995d65dcf1e0eL3-R3): Updated the version from `1.0.31` to `1.0.32` to reflect the new changes.
* [`archipelago/DK64Client.py`](diffhunk://#diff-2e2a10dbf06e376df9f46c4a4b442ccd5d63b70ef1bbaa8eacf0c26e5eb727f0R604-R633): Added `_cmd_taglink` and `_cmd_ringlink` methods to enable or disable `Taglink` and `Ringlink` features from the client. These methods update the corresponding flags in the context, modify client tags, …

Allow safety toggles

---

randomizer/CompileHints.py

Sorting the slam hint guarantees there's no arcane rules you can use to further decipher the location of the slams based on the world traversal mechanism used to build the hint.

Sort Slam Hint

---

__init__.py

Dirty fix that adds `dk64/__init__.py` to syspath. A better solution would be to use Pathlib for all the path code, but this change was my mvp to get the archipelago client to import.

Fix bug with Archipelago 0.6.1 client for linux where apworld root path is not added to syspath

---

__init__.py

Reverts 2dos/DK64-Randomizer#2661

Revert "Fix bug with Archipelago 0.6.1 client for linux where apworld root path is not added to syspath"

---

ap_version.py
archipelago/client/pj64.py

Sometimes, Windows likes to save file paths with non utf-8 characters (yay, ANSI!).  This can be a problem if someone ends up with file paths in their Project64.cfg with such a character.
We can solve this by at least trying latin-1 encoding, and only bail if that also fails. Tested using a config with é included.

Archipelago: Fall back to latin-1 encoding if utf-8 fails for the config file

---

__init__.py

Putting "Blueprints" somewhere in your yaml expands it during generation to mean all of the individual blueprints.
This basically only matters for itemlink, but it's nice quality of life for those who like to share GBs :)

Archipelago: Blueprints item group

---

.github/workflows/release_pages_dev.yml
.github/workflows/release_pages_main.yml

This pull request updates the GitHub Actions workflows for both the development and main release pipelines to automate the creation of a new release in the target repository whenever the `ap_version.py` file changes. The workflow now checks for changes to the version file, extracts the new version, and creates a corresponding release with the updated artifact.
**Release automation improvements:**
* Added a step to check if `ap_version.py` has changed in the latest commit, and only proceed with creating a release if it has. [[1]](diffhunk://#diff-49efdbf9bdda6b7a434332fac9b55ca8472a4b6a84246f87b1aee6ae5615fd8cR55-R90) [[2]](diffhunk://#diff-60f37cd8ba2c537fe1cd5f74155b09d679a6179d4766e1c0f607762f543146d6R52-R85)
* Added a step to extract the version number from `ap_version.py` using …

Adjust scripts and hope it works

---

__init__.py
archipelago/DK64Client.py
archipelago/Items.py

* More hint generation optimization
* Fix key 8 not being force-required
* Fix helm access switchsanity accidentally being all switches random
* Add progression balancing to barrier items
* Foreign rainbow coins now give coins correctly
* Starting keys now are actually shown in-game, not just in archipelago

AP misc fixes and opts

---

__init__.py
ap_version.py

Actually need to check if this is a DK world before checking the hint options in stage_generate_output

APWorld 1.1.7: Fix a silly crash

---

randomizer/Fill.py

We need shuffled_barrel_data to be populated with _something_ before Kasplat rando starts. So just populate it with the defaults and then shuffle it later.

Fix the interaction between Kasplat Rando and Bonus Barrel Rando

---

randomizer/Fill.py
randomizer/Patching/ItemRando.py

* Training moves should now show up at the start. Correctly. In all cases. I swear.
* Shopkeepers should now visually show up on the file select screen if they're unshuffled.

Fix starting training moves and shopkeepers

---

archipelago/Hints.py
randomizer/CompileHints.py
randomizer/Lists/WrinklyHints.py
randomizer/Patching/UpdateHints.py

No new functionality, just refactoring a bunch of code. Most lists got transferred into the Lists.WrinklyHints.py class and most classes got moved to CompileHints.py where possible.
The main feature added is the HintSet class, which I intend to be the vehicle in which hints are stored, assembled, and evaluated.
Next phase: moving the hint distribution into HintSet and asking the HintSet what the next type of hint to be generated should be

Refactor Hints Phase 1: HintSet

---

__init__.py
ap_version.py
archipelago/Items.py

* Fixed an issue where we weren't detecting moves already in the start_inventory for the purpose of random moves
* Fixed Climbing not being pushed if it's randomly chosen for starting moves
* Fixed duplicate pushing from start_inventory
* Treasure hurry treasures are now progression (skip balancing) if they aren't already progression for some other reason.

AP item fixes

---

randomizer/CompileHints.py
randomizer/ItemPool.py
randomizer/Settings.py
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

- Blueprint rewards beyond the cap are now treated as unshuffled locations and are always given GBs accordingly
- Foolish hints for blueprint reward regions past your cap can no longer appear

Excess BP Reward Simplification
