2dos/DK64-Randomizer

.github/dependabot.yml
.github/workflows/greetings.yml
.github/workflows/stale.yml
js/gui.js
level_progression.html
presets.py

switch from javascript to doing it in python

---

patches/asmFunctions.asm

Reverts 2dos/DK64-Randomizer#45
ROM fails to boot

Revert "ASM Update"

---

patches/asmFunctions.asm

Reverts 2dos/DK64-Randomizer#46

Revert "Revert "ASM Update""

---

patches/asmFunctions.asm

Reverts 2dos/DK64-Randomizer#48

Revert "Revert "Revert "ASM Update"""

---

randomize.py

Issue #113

---

js/gui.js

Reverts 2dos/DK64-Randomizer#115

Revert "Add some more try catches?"

---

form_data.py
index.html
js/rompatcher/MarcFile.js
js/rompatcher/RomPatcher.js
patch_files.py

https://github.com/2dos/DK64-Randomizer/issues/56

Automatically convert rom types

---

randomizer/CollectibleLogicFiles/AngryAztec.py
randomizer/CollectibleLogicFiles/TestBananaTotals.py
randomizer/Enums/Events.py
randomizer/Logic.py
randomizer/LogicClasses.py
randomizer/LogicFiles/AngryAztec.py

Also added a test python file to double check the banana totals for all levels

Angry Aztec banana logic

---

js.py
randomizer/ApplyRandomizer.py
randomizer/Settings.py
randomizer/ShuffleBarrels.py
randomizer/ShuffleExits.py
randomizer/ShuffleKasplats.py
randomizer/Spoiler.py
static/js/webworker_main.js
static/styles/styles.css
templates/base.html.jinja2
templates/nav-tabs.html.jinja2
templates/overworld.html.jinja2
templates/settings.html.jinja2
templates/spoiler.html.jinja2
tests/test_spoiler.py
ui/__init__.py
ui/generate_buttons.py
ui/rando_options.py

It moves the text printouts to the progressbar and entirely changes how we present the spoiler log.
Also I got rid of requiring a seed id. If you don't put one it'll make one, but you can make it anything now. Any string

Update Settings pages and progression bar

---

randomizer/Logic.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/LogicFiles/JungleJapes.py

Implemented IsBossBeatable to account for boss location & boss kong rando when determining access to bosses/boss keys

Logic for bosses

---

static/js/initalize.js
templates/base.html.jinja2
templates/difficulty.html.jinja2
templates/rando_options.html.jinja2
tools/prepare_offline.py
ui/__init__.py
ui/rando_options.py

Fixes up some of the offline builder process, it dosen't entirely solve some files that are being pulled from the web at the moment, but narrows down some of the issues.
It also re-adds cookie based settings loading.

Add in Cookie Loading/Offline Builds

---

randomizer/Patching/ApplyRandomizer.py
static/styles/gui.css
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2

Left aligned the form switches, fixed the typos, Split QOL into two tables so you don't need to scroll. Fixed the "Skip All" Helm option

Touched up some UI stuff and fixed typos. Helm Skip_All fix.

---

randomizer/Settings.py

Reordered definitions and calls so that random T&S wouldn't use an uninitialized variable

Bug fix in Settings.py

---

randomizer/Patching/CosmeticColors.py
randomizer/Patching/MusicRando.py

Fixed cosmetic 'Randomize All' switch

Fixed cosmetic 'Randomize All' switch

---

randomizer/Settings.py
templates/difficulty.html.jinja2
ui/rando_options.py

Added max values to Random Blockers and Troff and adjusted Troff and Scoff possible ranges

Added max values to Random Blockers and Troff

---

randomizer/Settings.py
templates/cosmetics.html.jinja2
templates/overworld.html.jinja2

- Reworked Keys required for K. Rool Key options to either require Key 8 through the form-switch or leave it completely up to chance using the Slider.
- Fixed Cookie Issue with "Randomize All" cosmetic switches.

Simplified KRool Slider and fixed Cookie issues

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Logic.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Settings.py
randomizer/Spoiler.py
static/presets/half.json
static/presets/hell.json
static/presets/open_except_end.json
static/presets/steady.json
static/presets/vanilla.json
templates/difficulty.html.jinja2
templates/overworld.html.jinja2
tests/test_spoiler.py
ui/__init__.py
ui/rando_options.py

Reverting due to many options being broken.

Revert "Added Starting Kongs Option. Changed Logic to account for this. Misc …"

---

randomizer/Fill.py
randomizer/Lists/WrinklyHints.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Patching/BarrelRando.py
randomizer/Settings.py
static/styles/gui.css
templates/difficulty.html.jinja2
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2
ui/__init__.py
ui/rando_options.py

- Changed UI Switch Colors to tell what is "On" easily
- Reorganized UI Options in better groups
- Added several Tooltips
- Oops All Beavers
- Disabled more options in UI based on Selection
- Re-worked Max Random Value for Blocker/Troff
- Minimum Blocker random value is 8, will change after you unfocus textbox
- Leaving a field blank will default to placeholder balues
- Disable Shop Hints

Misc UI changes

---

randomizer/Settings.py
randomizer/ShuffleBosses.py
templates/difficulty.html.jinja2

Adds a simple toggle below Hard Shooting, so that Donkey and Chunky will only be expected to fight Mad jack in boss kong shuffle if it's enabled.

Add hard mad jack toggle

---

randomizer/CompileHints.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Settings.py
static/presets/half.json
static/presets/hell.json
static/presets/open_except_end.json
static/presets/steady.json
static/presets/suggested.json
static/presets/vanilla.json
templates/frontpage.html.jinja2
templates/qualityoflife.html.jinja2
version.py

Updates the frontpage to match live
Updates the Hints to be a dropdown

Update hints and front page

---

static/styles/gui.css
templates/base.html.jinja2
templates/difficulty.html.jinja2
templates/frontpage.html.jinja2
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2

Tooltips now use Bootstrap's tooltips

Updated all tooltips to Bootrap tooltips.

---

static/styles/gui.css
templates/overworld.html.jinja2

Added custom CSS for disabled Sliders.
Clarified "Keys Required for K Rool" Tooltip

Added CSS for disabled Sliders

---

randomizer/Fill.py
ui/__init__.py
ui/rando_options.py

Fixed boss rando and move rando being forced on for Vanilla Level Order and fixed Vanilla fill fail in UI.
#409

Fixes Issue 409

---

randomizer/Patching/CosmeticColors.py
randomizer/Patching/generate_kong_color_images.py
static/js/izoColorPicker.js
static/styles/gui.css
static/styles/izoColorPicker.css
templates/base.html.jinja2
templates/cosmetics.html.jinja2
ui/__init__.py
ui/rando_options.py

Builds color_pallete dict, needs ROM writing

419 rgb picker

---

templates/rando_options.html.jinja2

Added to tooltip about high prices.
closes #426

Added note about High Prices.

---

static/styles/izoColorPicker.css
templates/cosmetics.html.jinja2

Fixed Cookies not keeping track of RGB, touched up CSS.

---

randomizer/Patching/CosmeticColors.py
randomizer/Settings.py
randomizer/Spoiler.py
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2

Added UI elements for Randomized Pickups and skipping Round 1 of Arcade.

---

static/styles/gui.css
templates/difficulty.html.jinja2

Added a checkbox to make sure Helm B Locker is Max Value.
closes #446

446 max amount

---

randomizer/Patching/CosmeticColors.py
templates/cosmetics.html.jinja2
ui/rando_options.py

- Reorganized Cosmetics Page
- Made sure there is a default color when no Cookies exist.
#419

Reorganized Cosmetics Page.

---

templates/rando_options.html.jinja2
ui/__init__.py
ui/rando_options.py

Clarified new Move settings and fix rando_options.py switches

Fixed some UI stuff with new moves dropdown.

---

randomizer/Patching/MiscSetupChanges.py
templates/overworld.html.jinja2
templates/rando_options.html.jinja2

Disabled Cross Kong Purchases and commented out Open Levels UI element until logic is done.

Disabled Cross Kong Purchases/Open Levels

---

randomizer/Patching/ApplyRandomizer.py
randomizer/Settings.py
templates/qualityoflife.html.jinja2

Added UI Element for Shorter Boss Fights

---

randomizer/Fill.py
randomizer/Lists/Exceptions.py
randomizer/ShuffleBosses.py

LZR seeds should generate more consistently now.
Also added a specific exception if a boss fails to place instead of an unhelpful index out of order

LZR Fixes with new logic

---

randomizer/Patching/EnemyRando.py

temporarily removing enemy shuffle from that one helm kremling barrel

---

randomizer/Patching/ApplyRandomizer.py
randomizer/Settings.py
templates/qualityoflife.html.jinja2

Added UI Element for Fast Warps

Added UI element for Fast Warps

---

randomizer/LogicFiles/GloomyGalleon.py

Slam not slam - this bricks all seeds right now

fixed typo

---

randomizer/Patching/ApplyRandomizer.py
randomizer/Patching/CosmeticColors.py
randomizer/Settings.py
randomizer/Spoiler.py

Added Random/Custom Colors to spoiler log.

---

randomizer/Patching/ApplyRandomizer.py

commented out errant code.

---

randomizer/Spoiler.py

fixed issue generating spoiler

---

randomizer/Lists/KasplatLocations.py
randomizer/ShuffleKasplats.py
tests/test_spoiler.py

Fixed a couple kasplat positions, removed some truly awful kasplats, and removed the name uniqueness problems.

fix some kasplat locations

---

tests/test_spoiler.py

undo test commit

---

randomizer/Patching/ApplyRandomizer.py
randomizer/Patching/MiscSetupChanges.py
randomizer/Settings.py
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2

Combined Skip Arcade 1 into Fast GBs.

---

randomizer/Lists/KasplatLocations.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/LogicFiles/JungleJapes.py
randomizer/Patching/EnemyRando.py
randomizer/Patching/KasplatLocationRando.py
randomizer/Settings.py
randomizer/ShuffleKasplats.py
static/presets/2dos_special.json
static/presets/coupled_lzr_balanced.json
static/presets/decoupled_lzr_balanced.json
static/presets/go_bananas.json
static/presets/hell.json
static/presets/level_order_balanced.json
static/presets/lo_rando_race.json
static/presets/suggested.json
static/presets/vanillaesque.json
templates/rando_options.html.jinja2

Added options for kasplat shuffling so we keep the 1.0 kasplat shuffle as a possibility.
Code was refactored in such a way so that the lambda checks remained booleans for speed.

Kasplat Shuffle Options

---

randomizer/Patching/CosmeticColors.py

Removed bongos from Klaptrap models.

---

randomizer/ItemPool.py
randomizer/Lists/Location.py

prevented issue where placing a shared move in Isles Cranky didn't block kong moves from being placed there

Isles Cranky exclusivity issue

---

randomizer/Fill.py

fixed issue where if tiny's cage starts open, any kong could be assigned to collect the gb

fixed tiny's freer gb

---

randomizer/Patching/EnemyRando.py

absolutely zero though in refactoring this, blasting this pr out as fast as possible with light testing

fix vanilla crown rando

---

randomizer/Settings.py

Added a scaling minimum that any given TnS could be. This is meant to make the "Max Value" you enter for the Random TnS to feel more accurate. Overall this will statistically increase CBs required. Can easily be tweaked. Will need community feedback.

Troff min scaling

---

randomizer/Fill.py
randomizer/Settings.py

2 issues fixed:
- The "Seagull Case" where you could get an un-fillable seed because both Diddy and Chunky are locked in Aztec
- Fixing incorrect calculation of Kong Items to be placed

Kong placement fixes

---

randomizer/Lists/CBLocations/AngryAztecCBLocations.py
randomizer/Lists/CBLocations/CreepyCastleCBLocations.py
randomizer/Lists/CBLocations/CrystalCavesCBLocations.py
randomizer/Lists/CBLocations/FranticFactoryCBLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CBLocations/GloomyGalleonCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py

Added function that sets the spawn point for custom balloons
Added missing names for CB groups

Add balloon spawn point

---

randomizer/Fill.py
randomizer/Prices.py
templates/overworld.html.jinja2
templates/rando_options.html.jinja2
ui/rando_options.py

Added extreme prices, where most moves are 10+ coins. The ranges were not picked to be consistent in seed generation, they were picked to be mean.
To assist LZR in these trying times it now reshuffles prices every 5th fill failure like the LO fill does.
Also adding some better debugging code.

Extreme Prices

---

index.html
static/styles/gui.css
templates/base.html.jinja2
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2

- UI now centered on bigger resolutions (even the main page...)
- Meta tags updated
- Added link to wiki for certain settings

UI not being centered on 4k monitors. Fixed Meta Tags.

---

randomizer/Fill.py

Fixes that issue where no logic + 5 kongs + unlock all moves would never successfully generate a seed.

fixed issue where no logic would check the logic

---

randomizer/Patching/CosmeticColors.py
randomizer/Patching/MusicRando.py
randomizer/Settings.py
randomizer/Spoiler.py
templates/base.html.jinja2
templates/difficulty.html.jinja2

Added cosmetics to the patch file and gave the ability to override them with the user's UI settings
#359

359 cosmetic patch

---

randomizer/Patching/CosmeticColors.py
static/styles/gui.css
templates/base.html.jinja2
templates/cosmetics.html.jinja2
ui/rando_options.py
ui/settings_strings.py

Fixed custom colors when overriding cosmetics. While patching a file only displays the Cosmetic and Settings Tabs.

Custom Color Fix, new File Patch UI

---

randomizer/ShuffleKasplats.py

This PR properly resets the kasplat location logic after a fail. I don't know how these fails happen but wow I'm glad it caught this error. I'm never talking shit about `KasplatPlacementException`s ever again.

Proper Kasplat Location Reset

---

randomizer/CompileHints.py

fix issue with referencing the starting kong list

bad kong list reference

---

randomizer/Settings.py

Better default for the owned kongs/moves lists

fix hints with moves and kongs unlocked

---

randomizer/ShuffleShopLocations.py

Japes Cranky and Japes Funky had reversed logic regions

fixed bad shop logic

---

randomizer/CompileHints.py

This fixes a couple issues with move hint placement logic. After this refactor, move hints should now be correctly placed before they are logically accessible. This can include scenarios like a hint in level 3 hinting Pineapple in level 1 before you free Chunky in level 3.
With the logic actually working, this can change the feel of the hint distribution - this will need user testing.

Correct Move Hint Placement

---

randomizer/Lists/CBLocations/FranticFactoryCBLocations.py

Factory bunch at the base of the block tower

Changed one 7 to a 4

---

randomizer/Fill.py

This update cuts the chaff from the Playthrough and now includes single GBs in the sphere that gives you access to the last B. Locker (usually Helm)

better single gbs in spoiler log

---

randomizer/Patching/EnemyRando.py

Prevent getout timer being set to 0

GetOut crash fix

---

ui/GenTracker.py

Back in the monkey saddle
Fixes GenTracker.py to check the now-multiple dictionaries for checks and loading zones so they're added to the HTML tracker properly

Fix HTML tracker for new spoiler format

---

rdb_editor.html

- Adds a page (./rdb_editor) which will take a .rdb file as an input, add the lines necessary to get DK64 Randomizer to function properly, then spit out a downlaod to the modified RDB. Output matches byte for byte with a modified version

RDB Editor page

---

randomizer/CompileHints.py

This PR corrects calculating the list of levels that have a T&S in level order seeds.

Prevent Excessively Useless T&S hints

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/DoorLocations.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/LogicFiles/JungleJapes.py
randomizer/Patching/DoorPlacer.py
randomizer/ShuffleDoors.py
randomizer/Spoiler.py
templates/spoiler.html.jinja2

Added logic for wrinkly and T&S door random locations.
Hint improvements TBD later, probably later in the 2.0 cycle.
This PR needed to make several improvements to `DoorLocations.py` so hopefully nobody is adding a huge amount of data there right this very second.

Door Rando Logic

---

randomizer/CompileHints.py

Fixed corner case where you could be stuck infinitely generating T&S hints.
Corner case requires:
- Very very few keys required (probably <2) 
- Random T&S values (needed to place T&S hints)
- Other settings that reduce hint categories present (and therefore increase prevalence of T&S hints)

Fix infinite tns hint generation

---

base-hack/Build/patch_text.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Item.py
randomizer/Patching/ItemRando.py
randomizer/Prices.py
randomizer/Settings.py
randomizer/ShuffleItems.py
randomizer/Spoiler.py
templates/rando_options.html.jinja2

Adds moves on GBs logic
`item_placement` returns to the spoiler until we come up with a better solution, it's kinda ugly
Maybe the flags work? None of this is tested with an actual seed.

added moves on gbs logic

---

randomizer/CompileHints.py

"Helm Room order is Diddy then Tiny then Donkey" becomes "The Blast-O-Matic can be disabled by using Diddy, then Tiny, then Donkey."
"K. Rool order is Lanky then Diddy then Chunky" becomes "King K. Rool will face off in the ring against Lanky, then Diddy, then Chunky."

Changing order hint text

---

randomizer/Patching/PriceRando.py
randomizer/ShuffleItems.py
randomizer/Spoiler.py

Spoiler will now have all items, better organized by level. Nothing should be missing anymore.
Also includes a small flag fix that might just fix everything??

fix item placement spoiler plus flag fix?

---

randomizer/Enums/VendorType.py
randomizer/Lists/Location.py
randomizer/ShuffleItems.py

Fixing shops in item rando by appropriately setting `is_shop`, `placement_index`, and having them appear in `spoiler.item_assignment`

fixing shops in item rando

---

randomizer/Fill.py
randomizer/LogicClasses.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/FranticFactory.py
randomizer/Patching/ItemRando.py
randomizer/Prices.py

Improvements on seed gen by removing some slowness issues
Includes some minor logic fixes found over the last few days

seed gen improvements and minor logic fixes

---

randomizer/Fill.py
randomizer/Settings.py
templates/rando_options.html.jinja2

Added phase2.1 setting (Shops, GBs, Keys, Blueprints)
Fixed issue where kasplat drops were too accessible in logic but not in game.

fix non-fta kasplat logic issues and new phase2.1

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Lists/Item.py

Added key location hints for item rando.
All keys that are required to be obtained have exactly one hint in or before the level they unlock. That hint door may or may not be reachable but it's in there.
Extremely lightly tested, good luck.

added key location hints for item rando

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/KasplatLocations.py
randomizer/Logic.py
randomizer/LogicFiles/AngryAztec.py
randomizer/Prices.py
randomizer/Settings.py
randomizer/ShuffleItems.py
randomizer/Spoiler.py

This PR should now establish prices inside shops correctly.
Be warned that in item rando there's a lot of things in shops, you may have more success with seed generation on lower price settings.

Complete Price Generation by Location

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py

Added hints that point at moves that are NOT required for the win condition

Foolish Hints

---

static/styles/gui.css
templates/cosmetics.html.jinja2
ui/rando_options.py

Re-organized Cosmetics page. Made Cosmetic Override switch hidden and always on.

Misc UI stuff for 2.0

---

randomizer/Fill.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/Settings.py
templates/overworld.html.jinja2

New setting to lock key 8 in helm. This only matters (and only does anything) if keys are to be shuffled.
Bundled in are various logic fixes and a crude attempt to make LZR fill more often.

Lock key 8 in helm

---

randomizer/Lists/CBLocations/CreepyCastleCBLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py

Added swim logic and added a few more instances of vines logic to the CB rando locations

Cb rando logic revision

---

randomizer/Lists/CrownLocations.py

Added the assumption that the B.o.M. has been shut down to all helm crowns that didn't already have it.

Helm crown logic corrections

---

randomizer/CompileHints.py
randomizer/Enums/Items.py
randomizer/Fill.py
randomizer/Lists/Item.py
randomizer/Logic.py
randomizer/ShuffleBosses.py
templates/difficulty.html.jinja2

Updated complex level progression to work with item rando. Updated hints to accompany this change, mainly increasing the general quality of hints.

Complex Level Progression

---

generate_rando_ui.py
randomizer/Enums/Types.py
randomizer/Patching/ApplyRandomizer.py
randomizer/Settings.py
templates/macros.html.jinja2
templates/overworld.html.jinja2
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2
ui/__init__.py
ui/rando_options.py

Added a starting key selector. Can now always edit Jetpac requirements.

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Minigame.py
randomizer/Settings.py

2 fixes:
- fixed issue where sometimes you could get barrels locking itself on a boss in complex LO
- fixed issue where key 8 wasn't WotH if it was locked in Helm

fixed complex boss rewards and locked key 8 in spoiler

---

randomizer/ShuffleWarps.py

Fixed issue where crossmap coupled warps were not being assigned correctly, erroring the fill

fix crossmap warps

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/ShuffleItems.py
templates/rando_options.html.jinja2
tests/test_spoiler.py

- Clarified path hints to actually say "path" - no idea why I didn't just do this in the first place
- Actually fixed vanilla prices

clarified hints

---

randomizer/CompileHints.py

oops wrong type

---

randomizer/Logic.py
tests/test_spoiler.py

fixed win condition for kapture mode

---

randomizer/Patching/EnemyRando.py

Fixed a bug where, if there were not enough non-disruptive enemies selected, the algorithm would freak out over the amount of disruptiveness going on. 
Also fixed my self-made error to now trigger when needed.

the bug fix, see description

---

randomizer/Lists/CrownLocations.py
randomizer/LogicFiles/HideoutHelm.py
randomizer/Patching/CrownPlacer.py

-Fixes a bug where crown pads would fail to spawn despite not having noItem as reward.
-Fixes a bug where the logic thinks the Roman Numeral doors need to be opened manually upon arriving in the B.o.M room in order to progress, regardless of helm settings.

Minor bug fixes

---

randomizer/Fill.py
randomizer/LogicFiles/JungleJapes.py

Fixed an issue where paring things from the WotH would not then trigger another round of paring, which could in some rare circumstances lead to unnecessary items in WotH.
Also fixed small Japes logic bug

Loop for WotH Paring

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Logic.py
randomizer/Settings.py
tests/test_spoiler.py

Adds a guaranteed hint for each helm door that is random
Some light tweaks to random doors:
- Minimum values to prevent completely trivial requirements
- Limitations on what types of items can randomly end up as a door requirement

Helm Door Hints

---

randomizer/Lists/CBLocations/CreepyCastleCBLocations.py
templates/base.html.jinja2
templates/cosmetics.html.jinja2
templates/frontpage.html.jinja2
templates/getting_started.html.jinja2
templates/macros.html.jinja2
templates/overworld.html.jinja2
templates/settings.html.jinja2

Fixes the cb group in Lanky's wind column to be more accessible (by moving it to a new location entirely)

Minor cb fix

---

randomizer/LogicFiles/FungiForest.py
randomizer/Settings.py
tests/test_spoiler.py

fixes an issue where the Bean couldn't be woth - most notably an issue when the bean is a helm door
also included is a very very minor logic fix for forest mill grinder activation

Fix Bean WotH

---

static/presets/default.json

forgot to add the new setting to the default so settings strings wouldnt break

ill remember this someday

---

randomizer/CompileHints.py
randomizer/Settings.py
randomizer/ShuffleBosses.py

Fixed issues related to starting with all moves:
- Fixed issue where you didn't get the camera ever
- Fixed issue where bosses would fail to place if you start with all moves
- Fixed hints to give reasonable hints. All keys now get a kong + level hint. These hints might still suck but it's something.

Fix starting with all moves

---

randomizer/Lists/CrownLocations.py
randomizer/Lists/Patches.py

-Fixes 2 dirt patches in Isles wrongly requiring vines 
-Fixes a crown pad's logic region being wrong

minor logic fixes

---

randomizer/Fill.py
tests/test_spoiler.py

woops: this fixes camera being able to be in foolish regions

the camera is definitely a major item

---

randomizer/Fill.py
randomizer/Patching/EnemyRando.py
randomizer/Patching/MusicRando.py
randomizer/Settings.py

Prevents Ice Traps from being on kasplats or dirt patches

Add bad Ice Trap location types

---

templates/settings.html.jinja2

Added a huge warning to strongly recommend people save their logs. Hopefully this saves some headache. A warning so nice I added it twice. We can hack this out closer to release or figure out how to dynamically show it later. Just want something in right now.

huge warning to save logs

---

randomizer/CollectibleLogicFiles/JungleJapes.py
randomizer/CompileHints.py
randomizer/Fill.py

- Oops all non-item rando seeds failed.
- Fixed an oversight making fairies foolish when the goal is all fairies
- Fixed logic around vanilla collectibles in the shellhive

some oopsies

---

randomizer/Settings.py
randomizer/ShuffleItems.py
tests/test_spoiler.py

- Fixed an issue where tough GBs were not included when the list selector was empty
- Also fixed seed gen failures when tough GBs were included

oops no tough gbs

---

randomizer/Logic.py
randomizer/ShuffleCBs.py

CB rando was editing the logic of the wrong files so the Fill was always using the vanilla cb logic. This fixes that cause that's real bad.

fix cb rando logic

---

randomizer/Fill.py
randomizer/Lists/CBLocations/CrystalCavesCBLocations.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
randomizer/LogicFiles/GloomyGalleon.py
randomizer/LogicFiles/JungleJapes.py

Simplified GetExitLevelExit which was weirdly high on the profiling tool. Hopefully this is a noticeable fill speed improvement.

Fill efficiency fix

---

randomizer/Fill.py
randomizer/Logic.py
randomizer/Prices.py

Fixed an issue with path generation were the assumptions made while calculating paths were incorrect or overwritten during the process of checking accessible locations.

Fix Path Assumptions

---

randomizer/Patching/MoveLocationRando.py

This should fix a long-dormant bug with microhints.

Changing errant tuples to lists

---

randomizer/CompileHints.py
randomizer/Fill.py

This is kind of just a bandaid fill fix to the process and should prevent impossible seeds from being generated. A proper solution is still TBD but I know where the problem likely lies.
Also bundled in here is deleting some useless code.

Impossible Fill Fix

---

randomizer/CompileHints.py

woah there that's a lotta errors

---

randomizer/Lists/Item.py
randomizer/Patching/CosmeticColors.py
randomizer/ShuffleItems.py

-Fixes an issue where the Nintendo Coin and the Rareware Coin would be swapped in the spoiler log
-Fixes an issue where the blueprints in the spoiler log do not correspond to the blueprint ingame (like Japes Diddy Blueprint being Castle Diddy Blueprint)
-Fixes an issue where Krusha's belt and bracers wouldn't be the color of the kong he replaces when his color isn't randomized.

Stop the swop

---

randomizer/CompileHints.py

Fixes an issue where a seed woud fail to generate if a K.Rool order hint was picked.

Fix seed gen error

---

randomizer/CompileHints.py
randomizer/Enums/Locations.py
randomizer/Fill.py
randomizer/LogicFiles/DKIsles.py
randomizer/Settings.py
tests/test_spoiler.py

it's not perfect, needs more work on corner cases and converting `start_with` to just maxing out the `starting_move_count`

start on arbitrary starting moves logic

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Settings.py
tests/test_spoiler.py

This _should_ fix all the issues with item rando on/off, starting moves, and shockwave statuses.

fix compatibility issues with starting moves, item rando, and shockwave

---

randomizer/Enums/Settings.py

Moving to int8 to save characters in the settings string.

Changing data type of starting_moves_count

---

static/js/initalize.js

https://github.com/2dos/DK64-Randomizer/issues/1068
This shouldn't work but it does.

I'm amazed this fixed it.

---

randomizer/Fill.py

Vanilla prices got me again. Didn't account for it in the new coin logic efficiency improvement.

fix issue with vanilla prices and new coin logic

---

randomizer/Lists/Minigame.py
randomizer/ShuffleBosses.py

- Krusha is now also no longer expected to do Mad Jack if he replaces Donkey or Chunky with Hard Bosses enabled
- Krusha is no longer expected to complete the medium dificulty Speedy Swing Sortie when replacing Donkey with Advanced Platforming enabled

Fix missed cases

---

randomizer/CompileHints.py
randomizer/ShuffleFairies.py

Fix fairy location rando - it was borked.
Also slightly tweak hint distribution to reduce guaranteed crappier hints.

Fix fairy location rando

---

randomizer/CompileHints.py
randomizer/Patching/ItemRando.py
wiki-lists/COINS.MD
wiki-lists/CROWNS.MD
wiki-lists/KASPLATS.MD
wiki-lists/PATCHES.MD

- Fixes a bug where seed gen would crash when trying to hint something being in the Rareware GB Room.
- Fixed a bug where generating a seed with Vanilla prices and Item Rando enabled, could cause the seed to not gen.

Minor fixes

---

randomizer/CompileHints.py
randomizer/Lists/KasplatLocations.py
randomizer/Lists/Location.py
randomizer/Lists/Patches.py
tests/test_spoiler.py
wiki-lists/KASPLATS.MD
wiki-lists/PATCHES.MD

- Better specified a couple locations that got too short from the last culling
- Fixed an issue that prevented entrance hints from generating correctly

fix entrance hints, correct a few locations

---

templates/overworld.html.jinja2

last second ui tooltip fixes

---

version.py

woah there buddy, what is 1.5 doing here

extremely important change

---

static/js/initalize.js

Noticed this bit of code was duplicated four times, so I separated it out.

Consolidating reused music loading code

---

static/presets/nostyle_allkeys.json
static/presets/qol_only.json

- NSAK now has a 40 medal jetpac requirement
- VBB will now no longer have cutscenes removed due to this preset being common for those playing the game for the first time in a while. Working on something more appropriate for this audience which enables cutscene skipping for 2.1

NSAK and VBB updates

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Fill.py
randomizer/Settings.py
randomizer/Spoiler.py

Converted existing path hints to multipath hints which hint all goals the hinted location is on the path to. The fixed hint preset has been slightly tweaked to account for the additional info you receive from these hints.
Also added the groundwork for spoiler hints. More work TBD on these.

Multipath Hints

---

randomizer/Lists/EnemyTypes.py
randomizer/Patching/EnemyRando.py

Unrando trashcan enemies

---

randomizer/Fill.py
randomizer/Lists/CustomLocations.py
randomizer/ShuffleCrates.py
randomizer/ShufflePatches.py
templates/spoiler.html.jinja2

- Add levels to spoiler log
- Levels are numbers right now
- Fix coming in a few hours hopefully

Melon crate location rando stuff

---

randomizer/CompileHints.py

i do not know why this broke but it is now fixed

---

static/presets/nostyle_allkeys.json
static/presets/sandbox.json
static/presets/season2.json
wiki-lists/CUSTOM_LOCATIONS.MD

- Fixed a bug where presets had different starting keys selected than intended.

Update preset settings strings

---

runner.py

Forgot to also change the name of the data variable so it wasn't showing up in race spoiler logs. This is now fixed.

Better spoiler hints for races

---

randomizer/Fill.py
randomizer/Settings.py
randomizer/Spoiler.py

Isolating some world altering settings so they don't get run mid-fill.
Also returning some of my precious debugging variables.

isolate some world altering settings

---

randomizer/ShuffleCBs.py
randomizer/ShuffleCoins.py
randomizer/ShuffleKasplats.py

Some old function was trying to be called, this is no longer the case.

correct the reset function on some shuffles

---

randomizer/Lists/DoorLocations.py
randomizer/ShuffleCrates.py
randomizer/ShuffleDoors.py
randomizer/ShuffleExits.py
randomizer/ShuffleFairies.py
randomizer/ShufflePatches.py

Many of the location shuffling algorithms weren't updating the new spoiler state. All is right in the world again and very shuffled seeds will gen once more.

custom location shuffle updates logic once more

---

randomizer/Fill.py
static/js/initalize.js
templates/base.html.jinja2

- Fixed an issue where CLO with keys on bosses would never succeed to fill.
- Added some advice on the dev site on what to do if you fail a bunch of attempts.

fix niche clo problem, added dev site failure advice

---

randomizer/Spoiler.py
runner.py

Swaps the runner.py from using multiprocess to doing generations directly in memory. Now that we have proper data passing this should be more efficent on the data transfer.

Un-Isolate generations

---

randomizer/Lists/CustomLocations.py
randomizer/Lists/EnemyTypes.py
randomizer/LogicFiles/CrystalCaves.py

-Enemies in Lanky's 5door Igloo can no longer have items, seeing as they're missable 
-Fixed bad crate/dirt location on the Caves TIny Kasplat platform (Kasplatform heh)

minor bug fix

---

randomizer/Patching/ApplyRandomizer.py

-Fixed an issue that prevents seeds from generating when the number of starting kongs is set to 5.

Winner's bracket

---

randomizer/CompileHints.py
static/js/initalize.js

oops I broke item hinting hints

---

randomizer/CompileHints.py

oops item hinting hints were still broken

---

randomizer/CompileHints.py
randomizer/Enums/HintType.py
randomizer/Enums/Plandomizer.py
randomizer/Enums/Settings.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/Exceptions.py
randomizer/Lists/Plandomizer.py
randomizer/Logic.py
randomizer/Patching/ApplyLocal.py
randomizer/Settings.py
randomizer/ShuffleBosses.py
randomizer/ShuffleExits.py
randomizer/ShuffleItems.py
randomizer/Spoiler.py
static/js/initalize.js
static/styles/styles.css
templates/plandomizer/plandomizer.html.jinja2
templates/plandomizer/plandomizer_general.html.jinja2
templates/plandomizer/plandomizer_hints.html.jinja2
templates/plandomizer/plandomizer_shops.html.jinja2
tests/test_spoiler.py
ui/generate_buttons.py
ui/plando_validation.py
ui/rando_options.py
ui/serialize_settings.py

It begins. Some things implemented:
- Picking items on locations
- Picking starting kongs
- Deciding what kongs open which cages
- Picking level order
- Picking K. Rool order
- Picking Helm order
- Creating custom hints
More to come later but this is a start
Other things fixed here:
- Mad Jack now correctly logically needs a slam when determining boss placement. This bug would not make seeds impossible, just in violation boss fill expectations.
- Finally condensed the two `FillKongsAndMovesFor-X` methods that really didn't need to be separate. They are now combined into `FillWorld`

Initial Plando Implementation

---

randomizer/Lists/CBLocations/JungleJapesCBLocations.py
randomizer/Lists/FairyLocations.py
wiki-lists/FAIRIES.MD

As before. JapesCBLocation linted that extra space, not appearing in my VSC

Small Fairy logic fix

---

randomizer/Enums/Events.py
randomizer/Fill.py
randomizer/Lists/BananaCoinLocations.py
randomizer/Lists/CustomLocations.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/GloomyGalleon.py
wiki-lists/COINS.MD
wiki-lists/CUSTOM_LOCATIONS.MD

- Fixed a bug where vines was not logically required to play instruments on top of the Llama's cage
- Added additional safeguards to make sure lava water does not make a seed unbeatable

guitar pad logic fix

---

static/js/initalize.js
templates/cosmetics.html.jinja2

We're adding music caching and doing some generic javascript formatting because I'm probably the last one who did that forever ago.

Add base music caching

---

randomizer/Fill.py

- Fixed a bug where King Kutout would be the boss in every level, but ofcourse only reward one single item.

Kut Out King in Kode?

---

randomizer/Fill.py
randomizer/Settings.py

i messed up that change up real bad in like two different spots
we go again

helm door crown goof

---

ui/serialize_settings.py

Hope it breaks less than it fixes.

fix non-plando

---

randomizer/CompileHints.py
static/js/initalize.js
templates/cosmetics.html.jinja2
templates/getting_started.html.jinja2
templates/plandomizer/plandomizer.html.jinja2
templates/progression.html.jinja2
templates/rando_options.html.jinja2
tests/test_spoiler.py
ui/__init__.py
ui/plando_settings.py
ui/plando_validation.py
ui/rando_options.py

- added slam prioritization on item hinting
- fixed a couple annoying css things around vanilla k. rool requirements
- added dev site checks for plando and widescreen
- added settings strings to plando jsons
- fixed plando json importing
- added shared move warning when shops are not in the pool

lots of things that annoyed me

---

randomizer/CollectibleLogicFiles/CrystalCaves.py
randomizer/Lists/BananaCoinLocations.py
randomizer/Lists/CBLocations/CrystalCavesCBLocations.py
randomizer/LogicFiles/CrystalCaves.py
static/presets/beginner.json
static/presets/preset_files.json
wiki-lists/COINS.MD
wiki-lists/COLORED_BANANAS.MD

- added beginner preset
- added (rocket or AP) to lower cabin

added beginner preset, lower cabin change

---

randomizer/CompileHints.py
randomizer/Enums/Settings.py
randomizer/Lists/Item.py
randomizer/LogicClasses.py
randomizer/LogicFiles/HideoutHelm.py
randomizer/Patching/UpdateHints.py
templates/qualityoflife.html.jinja2
tests/test_spoiler.py

- Added advanced item hinting: item hinting hints but only hinting the category of the item
- Fixed the Helm deathwarp location

advanced item hinting, helm deathwarp

---

templates/spoiler.html.jinja2

- Fixed a bug where the spoiler log items for the K.Rool phases were not uncollapsing when clicked.

K.Rool phase trick

---

index.html
randomizer.html
randomizer/Patching/ApplyLocal.py
static/js/initalize.js
templates/settings.html.jinja2
ui/generate_buttons.py

Makes it so we now have a download button for shared links so we no longer patch the seed on page load. Also modifys some loading data.

Modify the way shared links work

---

randomizer/Settings.py
runner.py

- Fixes indexing error when crown door is set to a non-random setting, but coin door is set to a random setting
- Fixes float + str operation error with spoiler log releases

Couple fixes

---

randomizer/LogicFiles/JungleJapes.py

- Removed Free Trade Agreement from logic for Japes Diddy Minecart, due to a bug with Chunky being unable to move after jumping

fix minecart FTA

---

.github/workflows/bump_version.yml

Major Release

---

randomizer/Fill.py

gotta not assume the items you're about to place
oops

shared moves accessibility fix

---

randomizer/PlandoUtils.py

Guns, instruments, camera and shockwave can all be placed on fairies now.

Plandomizer: increase the number of items that can be placed on fairies

---

randomizer/PlandoUtils.py

Camera can't be on a fairy

---

randomizer/CollectibleLogicFiles/GloomyGalleon.py
randomizer/Lists/CBLocations/GloomyGalleonCBLocations.py
randomizer/Lists/CustomLocations.py
randomizer/Lists/DoorLocations.py
randomizer/Lists/Minigame.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/DKIsles.py
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD
wiki/article_markdown/custom_locations/CustomLocationsDoors.MD
wiki/article_markdown/custom_locations/CustomLocationsMiscellaneous.MD

- Fix name for CustomLocation not behind the Galleon Punch GB Chest
- Updated logic for Caves Ice Castle to not expect DK to beat that game without Super Simian Slam or higher
- Updated Advanced Platforming logic to not incorrectly place things in logic.

Logic fixes, mainly advanced platforming

---

randomizer/Lists/Switches.py
randomizer/Patching/Lib.py
randomizer/Settings.py

This is in preparation for Switchsanity plando.

Moving Switch data to its own file

---

randomizer/Spoiler.py

Add balanced_krool_phases boolean to the spoilerlog.

Add "Balanced KRool Phases" to spoilerlog

---

randomizer/CompileHints.py
randomizer/Fill.py

I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate coins I hate …

Preventing the apocalypse

---

randomizer/PlandoUtils.py
templates/plandomizer/plandomizer_general.html.jinja2
ui/plando_validation.py

This lines up with the changes in 4.0 that allow for other bosses to appear as K. Rool phases.

Move K. Rool phases from "Kongs" to "Maps"

---

randomizer/Settings.py
randomizer/ShuffleBarrels.py

For plando:
Removed the != -1 checks where an empty list/dict wouldn't affect speed. Changed it to != []/{} where an empty list/dict would affect speed.

adapt to reality

---

randomizer/ShuffleDoors.py

- Fixed a bug where a 4th and possibly 5th portal would not spawn, because the code would think to place less portals.

portalAmountObeysPlando

---

CHANGELOG.MD
randomizer/CollectibleLogicFiles/CrystalCaves.py
randomizer/CollectibleLogicFiles/FranticFactory.py
randomizer/CollectibleLogicFiles/FungiForest.py
randomizer/Enums/Settings.py
randomizer/Lists/BananaCoinLocations.py
randomizer/Lists/CBLocations/CrystalCavesCBLocations.py
randomizer/Lists/CBLocations/FranticFactoryCBLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CustomLocations.py
randomizer/Lists/FairyLocations.py
randomizer/Lists/Logic.py
randomizer/Logic.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/CrystalCaves.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
wiki/article_markdown/custom_locations/CustomLocationsCoins.MD
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD
wiki/article_markdown/custom_locations/CustomLocationsFairies.MD
wiki/article_markdown/custom_locations/CustomLocationsMiscellaneous.MD

- Added Moontail to Glitched logic
- Krusha and Krool are exempt from it due to jump height differences
- Probably a lot more moontail tech out there, but these are the only ones I can think of

First implementation of Moontails

---

randomizer/Enums/MinigameType.py
randomizer/Enums/Settings.py
randomizer/Fill.py
randomizer/Logic.py
randomizer/LogicFiles/HideoutHelm.py
randomizer/Settings.py
randomizer/ShuffleBosses.py
randomizer/ShuffleExits.py
randomizer/Spoiler.py
templates/progression.html.jinja2
templates/rando_options.html.jinja2

Implemented logic for features already hack-complete:
- Chaos B. Lockers - UI is a little choppy but this needs a rework anyway, only supports already randomized B. Locker values (no fixed valuese)
- K. Rool phases in the boss pool
- Zero or One Helm barrel completion

chaos blockers, k rool bosses in pool

---

randomizer/Fill.py

WOOPS that list was NOT static

the gang averts a disastrous scouring

---

randomizer/Lists/EnemyTypes.py

- Fixed a bug where enemies with unintended additional logic could spawn in Tiny Temple Klaptrap room.

Ban Beefy Bandits

---

randomizer/Lists/Multiselectors.py
randomizer/LogicFiles/FungiForest.py
static/js/initalize.js
static/presets/preset_files.json
ui/generate_buttons.py
ui/rando_options.py

- Fixed Music Filtering and Disabled Songs multiselectors resetting on applying preset/importaing setting string
- Fixed music pack input always claiming to use cached music pack
- Fixed typo in Remove Barriers tooltip

cosmetic bug fixes

---

randomizer/Lists/Location.py
randomizer/ShuffleItems.py
templates/rando_options.html.jinja2

- Fixed seeds with isles colored bananas shuffled not generating

Fix isles medals flags

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Settings.py
randomizer/Spoiler.py

- Fixed seeds not generating when K.Rool phases is set to 5, with K.Rool phases in the boss pool
- Fixed seeds not generating when Kasplat rando is enabled with Isles cbs being enabled

4.0 gen fixes

---

randomizer/CompileHints.py
randomizer/Fill.py

Fixed a rare issue where some seeds would crash out while generating an unhinted score

hint score key fix (again)

---

randomizer/Settings.py

Added 8 instances of the word "Random" to the randomizer. Surely your seeds will be even more randomized. (fixed a bug that prevented some random win condition seeds to generate)

I'm so random

---

randomizer/Patching/CosmeticColors.py

- Fixes the writing of Krusha's head for shop indicators

Quick krusha head fix

---

base-hack/Build/BuildLib.py
base-hack/Build/heap.py
randomizer/Enums/Settings.py
randomizer/Lists/CustomLocations.py
randomizer/Lists/Warps.py
randomizer/Patching/BananaPortRando.py
randomizer/Settings.py
randomizer/ShufflePorts.py
tests/test_spoiler.py
wiki/article_markdown/custom_locations/CustomLocationsCoins.MD
wiki/article_markdown/custom_locations/CustomLocationsMiscellaneous.MD

- Warps will try to be useful as best they can.
- Oops I linted

coordinate progress

---

randomizer/ShufflePorts.py

-got rid of obsolete code
-forced python to report the bug (now fixed)

we have vanilla warps!

---

randomizer/Settings.py
templates/getting_started.html.jinja2

- Bananaport Location Shuffle is now off by default.

de faulty default fault

---

generate_rando_ui.py
randomizer/Lists/Plandomizer.py
templates/plandomizer/plandomizer_general.html.jinja2
ui/plando_validation.py

I don't know if the backend supports this yet, but now the frontend does.

Plandomizer: allow users to place level bosses on K. Rool phases

---

randomizer/Enums/Locations.py
randomizer/Enums/Types.py
randomizer/Lists/Location.py
randomizer/LogicFiles/DKIsles.py
randomizer/Patching/Lib.py
randomizer/Settings.py
randomizer/Spoiler.py

- Fixed a bug where you wouldn't start with climbing when choosing to start with climbing.

Start with all training fix

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/LogicClasses.py
static/presets/preset_files.json
tests/test_spoiler.py

Fixed new entrance hints:
- Coupled LZR will now follow the connectors back to a larger map and hint that entrance instead of a connector's entrance
- Entrances chosen for zones with more than one entrance are now significantly more likely to hint the first accessible entrance you will naturally encounter to that zone
The BLZR preset has been updated to better reflect what I like

Fixed new entrance hints

---

randomizer/Lists/CBLocations/FungiForestCBLocations.py
static/js/rando_options.js
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

some light js work
also a climbing logic fix (thanks revven)

fixed tns and blocker values being unusable

---

randomizer/CompileHints.py
randomizer/LogicFiles/CreepyCastle.py

- Fixed a logic bug where you were expected to climb ladders by going in and out of Castle's lower tunnel.
- Fixed a bug preventing seeds from generating with (advanced) item hinting if not enough locations are woth.

minor-fixes

---

randomizer/PlandoUtils.py
randomizer/ShuffleExits.py
ui/plando_validation.py

There were a couple of issues, one related to Helm and one related to enums.

Plandomizer: fix for level order

---

randomizer/CollectibleLogicFiles/FungiForest.py
randomizer/Lists/BananaCoinLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
wiki/article_markdown/custom_locations/CustomLocationsCoins.MD
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

Climbing logic fixes

---

randomizer/CollectibleLogicFiles/JungleJapes.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py
randomizer/LogicFiles/CreepyCastle.py
randomizer/LogicFiles/JungleJapes.py
wiki/article_markdown/custom_locations/CustomLocationsColoredBananas.MD

- Fixed Castle Tree not having a logical deathwarp
- Fixed Japes Chunky minigame, and the CB's in the tree in the Shellhive area not requiring climbing

You wouldn't fail to report a bug for a month

---

randomizer/Patching/ItemRando.py

Fixed an issue where some climbing locations could cause errors while patching

fixed a few climbings

---

randomizer/Fill.py
randomizer/ItemPool.py

hastily attempt to fix a bad key assumption, there are more known errors in here
specifically, currently looking into kongs locking themselves on hint doors

fix bad key assumption

---

randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Lists/DoorLocations.py
randomizer/Logic.py
templates/progression.html.jinja2
wiki/article_markdown/custom_locations/RandomSettingsDifficult.MD
wiki/article_markdown/custom_locations/RandomSettingsDifficultWithQolShuffle.MD
wiki/article_markdown/custom_locations/RandomSettingsEasy.MD
wiki/article_markdown/custom_locations/RandomSettingsStandard.MD

- Fixed the hilariously broken hint door accessibility check
- Fixed an issue where you would see the Key that was supposed to be in Helm as being there in the spoiler log but you also started with it so it's never actually there
- Rephrased the Helm Key Lock setting to better describe what it does in various settings

good lord what happened to hint door accessibility

---

randomizer/Patching/ASMPatcher.py

- Fixes a bug where gold beavers didn't correctly respond in Beaver Bother

Beavers weren't sufficiently bothered

---

randomizer/LogicFiles/DKIsles.py

fix top level krem issue

---

requirements-dev.txt
requirements.txt
tools/prepare_live.py

This pull request includes several improvements and bug fixes to the `tools/prepare_live.py` script. The changes focus on enhancing the handling of HTML resources, updating file links, and versioning JavaScript files.
Enhancements to HTML resource handling:
* Added a new import for the `re` module to enable regular expression operations.
* Introduced logic to load the version from `version.py` for appending version query parameters to JavaScript files.
* Renamed the variable `list` to `resources` in the `find_list_resources` function to improve code readability.
Updating file links and versioning:
* Added logic to append version query parameters to local JavaScript file links.
* Implemented a regex pattern to update JavaScript blocks with version query parameters and wrote the modified …

Update process for Discarding Javascript

---

.github/workflows/build_and_validate.yml
conftest.py
randomizer/Fill.py
randomizer/ItemPool.py
randomizer/Logic.py
randomizer/Patching/Lib.py

This pull request includes several changes to the `randomizer` module to improve performance and simplify logic checks. The most important changes include the introduction of caching for frequently called functions, the addition of a new helper function for location skipping logic, and various refactorings to streamline the codebase.
Performance improvements:
* [`randomizer/Fill.py`](diffhunk://#diff-916f131293a1569dcd9aed75a31fab8eed500c0d9358f95c1b8e6ad2a919d72eL122-R129): Added `@lru_cache` decorator to `GetExitLevelExit`, `GetLobbyOfRegion`, and `GetLevelExitTransition` functions to cache their results and improve performance. [[1]](diffhunk://#diff-916f131293a1569dcd9aed75a31fab8eed500c0d9358f95c1b8e6ad2a919d72eL122-R129) [[2]](diffhunk://#diff-916f131293a1569dcd9aed75a31fab8eed500c0d …

enable caching for generations

---

randomizer/Lists/FairyLocations.py

Thornvine fairy fix

---

randomizer/Lists/DoorLocations.py

- Fixed doors in thornvine barn to dusk only for portals
- Fixed door in library gauntlet : wrinkly only

Door fixes

---

randomizer/Lists/DoorLocations.py

- Lighthouse door logic fixed
- Added 3 more door locations (2 lighthouse, 1 library)

More door fixes

---

.gitignore
controller/app.py
docker-compose.yml
racetime_bot/Dockerfile
racetime_bot/randobot/dk64.py
racetime_bot/randobot/handler.py
randomizer/Fill.py
randomizer/Patching/ApplyRandomizer.py
worker/tasks.py
worker/worker.py

Update Racetime Bot and allow encryption

---

static/js/rando_options.js
static/styles/gui.css
templates/music.html.jinja2
templates/overworld.html.jinja2
templates/progression.html.jinja2
templates/qualityoflife.html.jinja2
templates/rando_options.html.jinja2

- Touch up a number of spots on the UI to have better spacing. Much of this is removing a couple unnecessary containers that were adding unnecessary spacing.
- Fixed a number of issues around toggles not being properly handled on UI updates, most notably when importing settings strings.

making the ui more consistent

---

randomizer.html
static/js/rando_options.js
templates/rando_options.html.jinja2

Fixed the buttons on the starting move selector so they'll actually function
Also added a "Vanilla Start" button to quickly apply that starting move selection

added quick actions to starting move selector

---

.gitignore
crowd_control/DonkeyKong64Randomizer.cs
crowd_control/test_dumps.py
randomizer/Patching/ASMPatcher.py
randomizer/Patching/Lib.py
templates/cosmetics.html.jinja2

- Disabled Holiday Mode
- Fixed the local copy of the Crowd Control CS File
- Jaku is fixing this on the Crowd Control side tomorrow
- Added a script to assist with debugging RAM dumps of Crowd Control sessions which get state locked
- Shortened the length of the wall of fire in Doga 2, making it more in-line with how it's done on PAL. This is to make this more doable with OHKO without the ledge grab strat

How the Grinch stole Holiday Mode

---

static/js/initalize.js
static/js/rando_options.js

This pull request includes several changes to improve the efficiency and readability of the JavaScript code in the `static/js/initalize.js` and `static/js/rando_options.js` files. The most important changes involve refactoring functions for better performance and clarity, as well as updating event listeners for consistency.
Refactoring and performance improvements:
* [`static/js/initalize.js`](diffhunk://#diff-2a83f41f58bc5257f5563b4d7893fbb64c2e7227169b21f0d56c5521be7999f1L502-R569): Refactored the `savesettings` and `savemusicsettings` functions to use modern JavaScript syntax, improve readability, and ensure async operations are handled correctly.
* [`static/js/initalize.js`](diffhunk://#diff-2a83f41f58bc5257f5563b4d7893fbb64c2e7227169b21f0d56c5521be7999f1L1183-R1293): Updated the …

Speed up UI selection speed

---

static/js/initalize.js

- Fixes an error that would prevent applying any of the default presets.

fix the thing

---

controller/Dockerfile
controller/app.py
controller/requirements.txt
docker-compose.yml
racetime_bot/Dockerfile
worker/Dockerfile
worker/requirements.txt

This reverts commit 39fe3190bfefeb00d81ac6c8a8e7142b66dd8baf.

Revert "Alpine docker (#2350)"

---

randomizer/CompileHints.py
randomizer/Settings.py

- Fixed an issue where No Logic + manually set B. Locker values (most notably seen in VBB) would result in 0'd B. Locker values
- Fixed an issue where starting shopkeepers could receive an item hinting hint

woah these shoulda been fixed way sooner

---

controller/Dockerfile
controller/app.py
controller/nginx-local.conf
controller/nginx.Dockerfile
controller/nginx.conf
controller/requirements.txt
docker-compose.yml
racetime_bot/Dockerfile
worker/Dockerfile
worker/requirements.txt
worker/worker.py

Reverts 2dos/DK64-Randomizer#2358

Revert "Alpine support"

---

static/js/init_variables.js
tools/prepare_live.py

This pull request includes significant changes to the `static/js/init_variables.js` and `tools/prepare_live.py` files to improve the loading and parsing of JSONC files. The most important changes include adding functionality to load and parse a compiled JSONC file, refactoring the parsing logic into a separate function, and enabling the `compress_jsonc` function.
Improvements to JSONC loading and parsing:
* [`static/js/init_variables.js`](diffhunk://#diff-a3cfbf764b4413752edd16d91d10c21bbc8f5e40317feb884e177a5d9d4f0e61R472-R509): Added functionality to load `compiled.jsonc` before other JSONC files and parse its content. This includes handling errors and ensuring the data is correctly parsed and processed.
* [`static/js/init_variables.js`](diffhunk://#diff-a3cfbf764b4413752edd16d91d10c21bb …

compress the jsonc

---

randomizer/Lists/MapsAndExits.py

woah there missed a spot

---

randomizer/ItemPool.py
randomizer/ShuffleBosses.py
templates/plandomizer/plandomizer_general.html

Boss plando actually works now
- Fixed an issue where boss plando might try placing two of the same boss
- Fixed an issue where boss plando broke plando settings imports
- Fixed an issue where plando would fix bosses in place regardless of whether or not you were plandoing bosses

wow how did this get past quality assurance

---

base-hack/Build/model_port.py
base-hack/src/pause/hint_renderer.py
randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Lists/DoorLocations.py

- Made the B. Locker value manual selection more intuitive with CLO enabled
- Removed a DK portal from the top of the lighthouse *(splat)*

better b locker value picking in clo

---

README.md
randomizer/Lists/DoorLocations.py
randomizer/LogicFiles/CrystalCaves.py
static/js/rando_options.js

- Fixed an issue where logic was not always properly applying to T&S transitions
- Fixed an issue where some settings (including VBB) would import incorrectly due to form validation

Fixed Door Logic

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/ShuffleWarps.py
randomizer/Spoiler.py

- Improved the path hint placement algorithm to more aggressively place hints in locations that are not locked by the hinted item
- Fixed an issue where Climbing was considered a useless move to the Helm Key location
- Rephrased the spoiler log around shuffled warps.  The list of what warps lead where should be significantly less confusing.

Better Path Hint Placement

---

static/js/rando_options.js

Fix plando loading

---

randomizer/Settings.py
static/js/generate_buttons.js
static/js/initalize.js
static/js/pyodide_functions.js
static/js/rando_options.js
ui/plando_settings.py

- Applying a plando settings file will apply the settings string within the file (if it contains one)
- Fixed an issue with the UI where Kong Rando could be incorrectly disabled, leading to fill failures

Never before have i been so rekt

---

controller/app.py
discord_bot/app.py
racetime_bot/randobot/handler.py
worker/worker.py

This pull request includes multiple changes across different files to standardize the default branch handling and improve the functionality of the randomizer and bot integrations. The most important changes include setting default branch values, updating URL handling based on branch, and re-enabling certain bot actions.
Standardizing default branch handling:
* [`controller/app.py`](diffhunk://#diff-f71b5fbaa07c5d55d81bc8bddc472b99dd904bf4d9b1964335d81dcff8d55b08L337-R337): Updated multiple functions (`get_presets`, `admin_presets`, `move_preset`) to set the default branch to "stable" instead of an empty string. [[1]](diffhunk://#diff-f71b5fbaa07c5d55d81bc8bddc472b99dd904bf4d9b1964335d81dcff8d55b08L337-R337) [[2]](diffhunk://#diff-f71b5fbaa07c5d55d81bc8bddc472b99dd904bf4d9b1964335d81dcff8d5 …

pre-prep changes

---

.bumpversion.cfg
controller/app.py
version.py

Dev to master

---

randomizer/CompileHints.py
randomizer/Fill.py
randomizer/Prices.py

- The "Taking Photos" key word is now correctly purple, even in multipath hints.
- Some stray partial fixes that don't completely fix any bugs without additional work

photos, now in color

---

randomizer/Fill.py
randomizer/Spoiler.py

- Fixed a bug that would prevent seeds from generating when starting with all of the training moves and with the DK Rap win condition selected

he can throw errors with relative ease

---

randomizer/Lists/Warps.py

- Moved bananaport data to correct region

Oh Bananaport

---

__init__.py
ap_version.py

- Added gen time, boss order, versions to the spoiler log, so we can figure out your bugs much more easily.
- Changed Fungi Time setting to Dusk for AP seeds

Spoiler stuff

---

ap_version.py
archipelago/Regions.py

- Factory Donkey Baboon Blast (or Arcade Round 1) can have items once again.

bring back baboon blast

---

__init__.py
ap_version.py
archipelago/DK64Client.py
archipelago/client/adapter.js
archipelago/client/pj64.py

This pull request includes several changes to the `__init__.py`, `ap_version.py`, `archipelago/DK64Client.py`, `archipelago/client/adapter.js`, and `archipelago/client/pj64.py` files. The changes aim to improve error handling, update versioning, and enhance the functionality of the DK64 client and Project64 client.
* Added a `display_error_box` function to show error messages using a message box. (`__init__.py`: [__init__.pyR31-R39](diffhunk://#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cR31-R39))
* Wrapped the `copy_dependencies` function with a try-except block to handle `PermissionError` and display an error message. (`__init__.py`: [__init__.pyR83-R85](diffhunk://#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cR83-R85))
* Changed …

Various adjustments

---

ap_version.py
archipelago/DK64Client.py
archipelago/client/pj64.py

This pull request introduces several enhancements and fixes across multiple files, including version updates, new features for tracking scouted locations in `DK64Client`, improved error handling in `pj64.py`, and minor code refinements. Below is a breakdown of the most important changes:
* Updated the version in `ap_version.py` from `1.0.14` to `1.0.15` to reflect the new changes.
* Added a `locations_scouted` dictionary to track scouted locations and their associated item/player information. This is used in `readChecks` to append scouted data to `sent_checks`. [[1]](diffhunk://#diff-2e2a10dbf06e376df9f46c4a4b442ccd5d63b70ef1bbaa8eacf0c26e5eb727f0R34) [[2]](diffhunk://#diff-2e2a10dbf06e376df9f46c4a4b442ccd5d63b70ef1bbaa8eacf0c26e5eb727f0R370-R371) …

Adjust how we check data

---

ap_version.py
archipelago/client/adapter.js
archipelago/client/pj64.py

This pull request introduces several enhancements and fixes to improve error handling, logging, and configuration management for the Project64 client and server adapter. The most notable changes include better server startup error handling, improved logging for user guidance, and streamlined configuration setup for Project64.
* Enhanced logging in `archipelago/client/adapter.js` to provide detailed messages during server startup, including success and error scenarios. Added specific handling for port binding errors with user alerts.
* Improved logging in `archipelago/client/pj64.py` to guide users on proper setup, including recommendations to start Project64 through the client and run the client as an administrator.
* Added a `socket.timeout` exception handler in `_send_command` to …

Add some AGGRESSIVE messaging

---

ap_version.py
archipelago/DK64Client.py
archipelago/client/common.py

Sends Map IDs to Client for use with Poptracker

Thanks Seagull

---

__init__.py
ap_version.py
archipelago/Options.py

- Added the following new settings:
- Helm Phase Count
- Krool Phase Count
- CBs required for Medal
- Mermaid Pearl Requirement
- Jetpac Medal Requirement
- Rareware Door Requirement
- Krool Key Count (So you can do random keys)
- Changed order of yaml to look nicer

More Settings

---

__init__.py
ap_version.py
archipelago/Options.py
archipelago/Regions.py
randomizer/LogicFiles/AngryAztec.py
randomizer/LogicFiles/DKIsles.py
randomizer/LogicFiles/FranticFactory.py
randomizer/LogicFiles/FungiForest.py
templates/overworld.html

Added the following:
- Custom Barriers
- Hard Shooting
- Shuffled Jetpac Enemies
- Hard Enemies
- Memory Challenge (lol)
- Strict Helm Timer
- Mirror Mode (lmao even)
Logic Fixes:
- Added AvP way to get from Mushroom Area to LowerExterior
- Added phaseswim as a valid way to get to Thornvine region

New Settings

---

randomizer/CollectibleLogicFiles/JungleJapes.py

changed 7 tiny cbs beyond rambi gate to 5 beyond rambi gate and 2 beyond coconut gate 2

Move two tiny cbs from BeyondRambiGate to BeyondCoconutGate2

---

__init__.py
ap_version.py
archipelago/Items.py
archipelago/Logic.py
archipelago/Regions.py

- Fixed the False alarm error of "accessability check failed" or something. If that error comes up again, ALWAYS REPORT IT from now on.
- Fixed the odd "List index out of range" error that'd sometimes brick seed gen. (in theory)

Multithread Drifting

---

ap_version.py
archipelago/Logic.py

- Fixed a bug where X items win conditions would break and fail to generate in AP.

Misc item fixes

---

ap_version.py
archipelago/Items.py

Fixes starting key list by removing keys from the world

Fix starting key list

---

__init__.py
ap_version.py

Filter out event locations from hint generation, this will speed up generation quite significantly since we have a LOT of event locations.

AP: hint generation optimization

---

ap_version.py
base-hack/src/item rando/spawning.c

- Fixed a bug where a Keg in the back of mill made a bonus barrel in Crystal Caves think it should spawn Lanky Kong upon completion.

Fix Lanky Keg

---

.vscode/tasks.json
ap_version.py
archipelago/DK64Client.py

Added package apworld as a vscode task (yes im that lazy)
removed 2 tabs on the DK64 client

remove tabs

---

static/styles/gui.css

Resizable multi-select dropdowns. Default full width sizing when displaying multi-select dropdowns. Highlights checked items in list. Added CSS to preserve hover color when item is checked.

Resizable MS dropdowns. Default full width sizing. Highlights checked

---

randomizer/Patching/ItemRando.py

* Fixes an issue where training moves will just disappear if they are shuffled but you start with all of them.

Another training moves fix

---

__init__.py
ap_version.py
archipelago/Options.py

* You can now select your starting kong in AP.

Add starting kong selection to AP

---

randomizer/Lists/CBLocations/AngryAztecCBLocations.py
randomizer/Lists/CBLocations/FranticFactoryCBLocations.py
randomizer/Lists/CBLocations/FungiForestCBLocations.py
randomizer/Lists/CBLocations/JungleJapesCBLocations.py

* Fix CBs requiring specific Kongs even if they are a different color, creating a logical impossibility.

Fix custom CB logic

---

archipelago/FillSettings.py

I am genuinely unsure how this ever worked.

Fix starting shopkeepers
